### ISSUE TITLE
django.db.migrations.exceptions.NodeNotFoundError: Migration accounts.0016_add-api-keys  dependencies reference nonexistent parent node (u'authtoken', u'0001_initial')

### ISSUE THREAD

**Issue by whedro** [nijel/weblate#1048]
Hi nijel, 
after git pull i have this error

django.db.migrations.exceptions.NodeNotFoundError: Migration accounts.0016_add-api-keys  dependencies reference nonexistent parent node (u'authtoken', u'0001_initial')

### Steps to reproduce
1. git pull
2. Django REST Frameword MISSING WARNING
3. pip install --upgrade -r requirements.txt
4. pip install --upgrade -r requirements-optional.txt
5. sudo ./manage.py migrate

### Actual behaviour

/usr/local/lib/python2.7/dist-packages/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

/usr/local/lib/python2.7/dist-packages/django/template/utils.py:37: RemovedInDjango110Warning: You haven't defined a TEMPLATES setting. You must do so before upgrading to Django 1.10. Otherwise Django will be unable to load templates.
  "unable to load templates.", RemovedInDjango110Warning)

Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/makemigrations.py", line 65, in handle
    loader = MigrationLoader(None, ignore_no_migrations=True)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 306, in build_graph
    _reraise_missing_dependency(migration, parent, e)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 276, in _reraise_missing_dependency
    raise exc
django.db.migrations.exceptions.NodeNotFoundError: Migration accounts.0016_add-api-keys dependencies reference nonexistent parent node (u'authtoken', u'0001_initial')

### Server configuration

/usr/local/lib/python2.7/dist-packages/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

/usr/local/lib/python2.7/dist-packages/django/template/utils.py:37: RemovedInDjango110Warning: You haven't defined a TEMPLATES setting. You must do so before upgrading to Django 1.10. Otherwise Django will be unable to load templates.
  "unable to load templates.", RemovedInDjango110Warning)

 * Weblate weblate-2.5-197-g3329ea1
 * Python 2.7.6
 * Django 1.9.4
 * six 1.10.0
 * python-social-auth 0.2.14
 * Translate Toolkit 1.14.0-rc1
 * Whoosh 2.7.3
 * Git 1.9.1
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.2
 * lxml 3.6.0
 * django-crispy-forms 1.6.0
 * compressor 1.6
 * djangorestframework 3.3.3
 * pyuca N/A
 * pyLibravatar N/A
 * Mercurial 3.7.3
 * Database backends: django.db.backends.mysql

**Comment by nijel** [comment]
There is new dependency, you need to adjust settings.py a well on upgrade.

**Comment by whedro** [comment]
yop, .. my bad .. I forgot on settings.py changed .. (by diff with settings_example.py)
Thanks, ... now is it right.
