### ISSUE TITLE
Internal Server Error on OpenShift after setting WEBLATE_SITE_TITLE

### ISSUE THREAD

**Issue by saad440** [nijel/weblate#1050]
After setting the environment variable WEBLATE_SITE_TITLE on an OpenShift instance to set custom site title and restarting the app, an internal server error occurs.
### Steps to reproduce
1. rhc -aweblate env set WEBLATE_SITE_TITLE='Custom Title'
2. rhc -aweblate app stop
3. rhc -aweblate app start
4. Visit the weblate site

### Expected behaviour
Weblate should run fine with the site title set to 'Custom Title'.

### Actual behaviour
Internal Server Error

### Server configuration
 * Weblate 2.6-dev
 * Python 2.7.8
 * Django 1.8.12
 * six 1.10.0
 * python-social-auth 0.2.14
 * Translate Toolkit 1.14.0-rc1
 * Whoosh 2.7.3
 * Git 1.8.2.1
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.2
 * lxml 3.4.4
 * django-crispy-forms 1.6.0
 * compressor 1.6
 * djangorestframework 3.3.3
 * pyuca N/A
 * pyLibravatar N/A
 * Mercurial 3.7.3
 * Database backends: django.db.backends.sqlite3

**Comment by nijel** [comment]
Can you please share error from the server logs?

**Comment by saad440** [comment]
I don't have access to /var/log. Where else do I look for the server logs?

**Comment by saad440** [comment]
Okay. Found it in app-root/logs/python.log.
This is what happens after restarting:

```
[Sun Apr 03 16:44:29 2016] [notice] caught SIGWINCH, shutting down gracefully
[Sun Apr 03 16:44:54 2016] [notice] Digest: generating secret for digest authentication ...
[Sun Apr 03 16:44:54 2016] [notice] Digest: done
[Sun Apr 03 16:44:54 2016] [notice] Apache/2.2.15 (Unix) mod_wsgi/3.4 Python/2.7.8 configured -- resuming normal operations
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1] mod_wsgi (pid=376713): Target WSGI script '/var/lib/openshift/57011d9e2d5271e1640000ac/app-root/runtime/repo/wsgi/application' cannot be loaded as Python module.
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1] mod_wsgi (pid=376713): Exception occurred processing WSGI script '/var/lib/openshift/57011d9e2d5271e1640000ac/app-root/runtime/repo/wsgi/application'.
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1] Traceback (most recent call last):
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]   File "/var/lib/openshift/57011d9e2d5271e1640000ac/app-root/runtime/repo/wsgi/application", line 35, in <module>
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]     application = get_wsgi_application()
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]   File "/var/lib/openshift/57011d9e2d5271e1640000ac/python/virtenv/lib/python2.7/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]     django.setup()
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]   File "/var/lib/openshift/57011d9e2d5271e1640000ac/python/virtenv/lib/python2.7/site-packages/django/__init__.py", line 17, in setup
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]   File "/var/lib/openshift/57011d9e2d5271e1640000ac/python/virtenv/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]     self._setup(name)
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]   File "/var/lib/openshift/57011d9e2d5271e1640000ac/python/virtenv/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]     self._wrapped = Settings(settings_module)
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]   File "/var/lib/openshift/57011d9e2d5271e1640000ac/python/virtenv/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]   File "/opt/rh/python27/root/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]     __import__(name)
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]   File "/var/lib/openshift/57011d9e2d5271e1640000ac/app-root/runtime/repo/weblate/__init__.py", line 23, in <module>
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]     from weblate.requirements import (
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]   File "/var/lib/openshift/57011d9e2d5271e1640000ac/app-root/runtime/repo/weblate/requirements.py", line 28, in <module>
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]     from weblate.trans.vcs import GitRepository, HgRepository
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]   File "/var/lib/openshift/57011d9e2d5271e1640000ac/app-root/runtime/repo/weblate/trans/vcs.py", line 39, in <module>
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]     from weblate.trans.util import get_clean_env, add_configuration_error
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]   File "/var/lib/openshift/57011d9e2d5271e1640000ac/app-root/runtime/repo/weblate/trans/util.py", line 30, in <module>
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]     from django.core.cache import cache
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]   File "/var/lib/openshift/57011d9e2d5271e1640000ac/python/virtenv/lib/python2.7/site-packages/django/core/cache/__init__.py", line 34, in <module>
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]     if DEFAULT_CACHE_ALIAS not in settings.CACHES:
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]   File "/var/lib/openshift/57011d9e2d5271e1640000ac/python/virtenv/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]     self._setup(name)
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]   File "/var/lib/openshift/57011d9e2d5271e1640000ac/python/virtenv/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]     self._wrapped = Settings(settings_module)
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]   File "/var/lib/openshift/57011d9e2d5271e1640000ac/python/virtenv/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]   File "/opt/rh/python27/root/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]     __import__(name)
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]   File "/var/lib/openshift/57011d9e2d5271e1640000ac/app-root/runtime/repo/weblate/settings_openshift.py", line 121, in <module>
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]     import_env_vars(os.environ, sys.modules[__name__])
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]   File "/var/lib/openshift/57011d9e2d5271e1640000ac/app-root/runtime/repo/weblate/openshiftlib.py", line 62, in import_env_vars
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]     ast.literal_eval(Template(value).substitute(environ)))
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]   File "/opt/rh/python27/root/usr/lib64/python2.7/ast.py", line 49, in literal_eval
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]     node_or_string = parse(node_or_string, mode='eval')
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]   File "/opt/rh/python27/root/usr/lib64/python2.7/ast.py", line 37, in parse
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]     return compile(source, filename, mode, PyCF_ONLY_AST)
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]   File "<unknown>", line 1
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]     Translation Server
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1]                      ^
[Sun Apr 03 16:45:16 2016] [error] [client 127.9.183.1] SyntaxError: unexpected EOF while parsing
39.43.117.126 - - [03/Apr/2016:16:45:16 -0400] "GET / HTTP/1.1" 500 626 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
```

**Comment by nijel** [comment]
Ah now I see it. The variable is used unescaped in the settings (to allow passing more complex Python constructs, see ,https://docs.weblate.org/en/latest/admin/deployments.html#customize-weblate-configuration) you need to add quotes around it:

```sh
rhc -aweblate env set WEBLATE_SITE_TITLE='"Custom Title"'
```

**Comment by saad440** [comment]
Yeah it does work. Though I think the documentation should be a bit clearer about why we need to add quotes. After all, SITE_TITLE is not the only string variable that Weblate uses.

**Comment by nijel** [comment]
Indeed with string variables it's not obvious.
