### ISSUE TITLE
Upgrade to 2.5 from 2.5-dev

### ISSUE THREAD

**Issue by ddxdental** [nijel/weblate#1077]
Hi,

I am upgrading to the final 2.5 from a 2.5 pre-release.  Running through the generic upgrade path, I hit an error related to django installed (1.7.9) being to old.  No problem, I did a pip install that bumped me to 1.9.5.  Now I am getting an "Apps aren't loaded yet." error.

Any ideas?

Thanks,

Mike

```
/srv/weblate/manage.py list_versions
Traceback (most recent call last):
  File "/srv/weblate/manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/dist-packages/social/apps/django_app/__init__.py", line 14, in <module>
    from social.apps.django_app.utils import load_strategy
  File "/usr/lib/python2.7/dist-packages/social/apps/django_app/utils.py", line 20, in <module>
    Strategy = module_member(STRATEGY)
  File "/usr/lib/python2.7/dist-packages/social/utils.py", line 23, in module_member
    module = import_module(mod)
  File "/usr/lib/python2.7/dist-packages/social/utils.py", line 17, in import_module
    __import__(name)
  File "/srv/weblate/weblate/accounts/strategy.py", line 25, in <module>
    from social.strategies.django_strategy import DjangoStrategy
  File "/usr/lib/python2.7/dist-packages/social/strategies/django_strategy.py", line 4, in <module>
    from django.contrib.contenttypes.models import ContentType
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/contenttypes/models.py", line 161, in <module>
    class ContentType(models.Model):
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

**Comment by nijel** [comment]
Try upgading python-social-auth as well, that should fix it.

**Comment by ddxdental** [comment]
Yup.  Thanks!
