### ISSUE TITLE
Trying to upgrade to 2.5 but got migrate errors 

### ISSUE THREAD

**Issue by murhafh** [nijel/weblate#1082]
### Steps to reproduce
1. From version 2.1 update all requirements 
2. Update settings.py file based on example file
3. run ./manage.py migrate

### Actual behaviour
Got an error "Table 'weblate.accounts_autogroup' doesn't exist"

### Expected behaviour
Migration complete

### Server configuration
Weblate weblate-2.5-2-gb0dcef3
 * Python 2.7.3
 * Django 1.9.5
 * six 1.10.0
 * python-social-auth 0.2.16
 * Translate Toolkit 1.13.0
 * Whoosh 2.7.4
 * Git 2.2.1
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.0
 * lxml 3.6.0
 * django-crispy-forms 1.6.0
 * compressor 2.0
 * pyuca N/A
 * pyLibravatar N/A
 * Mercurial 3.2.4
 * Database backends: django.db.backends.mysql

**Comment by nijel** [comment]
Probably everybody updates more frequent that this big distance :-).

Can you please provide full log of the migration?

Anyway you can probably workaround it by migrating accounts first:

     ./manage.py migrate accounts

**Comment by murhafh** [comment]
Trying to do ./manage.py migrate accounts will result in the same error. Here is the full trace, please advise if there is some other logs I can find:

Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/weblate.worldfirst.local/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/var/www/weblate.worldfirst.local/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/weblate.worldfirst.local/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/weblate.worldfirst.local/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/var/www/weblate.worldfirst.local/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    emit_post_migrate_signal(self.verbosity, self.interactive, connection.alias)
  File "/var/www/weblate.worldfirst.local/local/lib/python2.7/site-packages/django/core/management/sql.py", line 50, in emit_post_migrate_signal
    using=db)
  File "/var/www/weblate.worldfirst.local/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 192, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/var/www/weblate.worldfirst.local/weblate/weblate/accounts/models.py", line 1023, in sync_create_groups
    create_groups(False)
  File "/var/www/weblate.worldfirst.local/weblate/weblate/accounts/models.py", line 905, in create_groups
    if not AutoGroup.objects.filter(group=group).exists():
  File "/var/www/weblate.worldfirst.local/local/lib/python2.7/site-packages/django/db/models/query.py", line 651, in exists
    return self.query.has_results(using=self.db)
  File "/var/www/weblate.worldfirst.local/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 501, in has_results
    return compiler.has_results()
  File "/var/www/weblate.worldfirst.local/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 819, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/var/www/weblate.worldfirst.local/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 848, in execute_sql
    cursor.execute(sql, params)
  File "/var/www/weblate.worldfirst.local/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/var/www/weblate.worldfirst.local/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/var/www/weblate.worldfirst.local/local/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/var/www/weblate.worldfirst.local/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/var/www/weblate.worldfirst.local/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 112, in execute
    return self.cursor.execute(query, args)
  File "/var/www/weblate.worldfirst.local/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/var/www/weblate.worldfirst.local/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.ProgrammingError: (1146, "Table 'weblate.accounts_autogroup' doesn't exist")

**Comment by nijel** [comment]
Try applying following patch, that should help:

```
diff --git a/weblate/accounts/models.py b/weblate/accounts/models.py
index 03c0407..61d5ad7 100644
--- a/weblate/accounts/models.py
+++ b/weblate/accounts/models.py
@@ -904,9 +904,6 @@ def create_groups(update):
             Permission.objects.get(codename='use_mt'),
         )
 
-    if not AutoGroup.objects.filter(group=group).exists():
-        AutoGroup.objects.create(group=group, match='^.*$')
-
     owner_permissions = (
         Permission.objects.get(codename='author_translation'),
         Permission.objects.get(codename='upload_translation'),
```

Once the migration is done, you can revert it and run the migration again.

I think this is caused by too strict dependencies and it will take me some time to figure out proper solution...

**Comment by murhafh** [comment]
Thank you, I tried that, but now I'm getting unknown columns errors:
django.db.utils.OperationalError: (1054, "Unknown column 'accounts_profile.hide_source_secondary' in 'field list'")
django.db.utils.OperationalError: (1054, "Unknown column 'accounts_profile.dashboard_view' in 'field list'")

I'm trying to manually add these to the DB but I'm afraid this might also cause problems, is there a schema for the database in the documentation somewhere that I can try to match?

**Comment by nijel** [comment]
Did you upgrade from older Django version as well in same step? I guess that will be cause of the problems as this was always problematic and together with so many migration probably caused this. There are quite some information on this in [our documentation](https://docs.weblate.org/en/latest/admin/upgrade.html#upgrade-from-2-1-to-2-2). Maybe doing the upgrade in smaller steps will be better.

As for the SQL dump it's not really documented and I also think it will be quite hard to fix it manually. Anyway you can find it here: [schema.txt](https://github.com/nijel/weblate/files/228038/schema.txt)

**Comment by nijel** [comment]
As for the latest error, it can be probably again workarounded:

```patch
diff --git a/weblate/accounts/models.py b/weblate/accounts/models.py
index 03c0407..c58cbb7 100644
--- a/weblate/accounts/models.py
+++ b/weblate/accounts/models.py
@@ -968,8 +968,6 @@ def create_groups(update):
             username=ANONYMOUS_USER_NAME,
             is_active=False,
         )
-    # Ensure anonymous user has profile
-    Profile.objects.get_or_create(user=anon_user)
 
     if created or update:
         anon_user.set_unusable_password()
```

**Comment by nijel** [comment]
I think I've fixed both issues in git now. It would be great if you could test it, but it would mean you have to upgrade to git version as otherwise the migrations will be really messy.

**Comment by murhafh** [comment]
So I need to checkout the master branch and rerun the migrations?

**Comment by murhafh** [comment]
I tried adding the new migration files to the 2.5 version I have and run the migrate. Now I'm hitting this:

File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/weblate.worldfirst.local/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/var/www/weblate.worldfirst.local/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/weblate.worldfirst.local/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/weblate.worldfirst.local/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/var/www/weblate.worldfirst.local/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 89, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/var/www/weblate.worldfirst.local/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/var/www/weblate.worldfirst.local/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/var/www/weblate.worldfirst.local/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 306, in build_graph
    _reraise_missing_dependency(migration, parent, e)
  File "/var/www/weblate.worldfirst.local/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 276, in _reraise_missing_dependency
    raise exc
django.db.migrations.exceptions.NodeNotFoundError: Migration accounts.0016_add-api-keys dependencies reference nonexistent parent node (u'authtoken', u'0001_initial')

**Comment by nijel** [comment]
You need to update settings, new apps have to be added to INSTALLED_APPS (for API).

**Comment by nijel** [comment]
Ouch and there was bug in the new migration, I've just fixed it...

**Comment by nijel** [comment]
...and adding migrations to old code will not really work in the end - the database structure has quite evolved...

**Comment by murhafh** [comment]
Thank you I managed finally to get the migrations working. I had to alter the database manually a few times but in the end it works

**Comment by nijel** [comment]
Sorry for the troubles. Migrations for more than one release are really not tested...
