### ISSUE TITLE
DoesNotExist: Group matching query does not exist.

### ISSUE THREAD

**Issue by martinpucik** [nijel/weblate#1089]
### Steps to reproduce
1. Change user group
2. Try to access component's language
3. Weblate throws Internal Server Error

### Error stacktrace:

```python
weblate[7174]: ERROR Internal Server Error: /translate/annie/app/ar/
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/share/weblate/weblate/trans/views/edit.py", line 598, in translate
    'addword_form': InlineWordForm(),
  File "/usr/share/weblate/weblate/trans/util.py", line 298, in render
    return django_render(request, template, context, status=status)
  File "/usr/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 53, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "/usr/lib/python2.7/site-packages/django/template/loader.py", line 114, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "/usr/lib/python2.7/site-packages/django/template/engine.py", line 244, in render_to_string
    return t.render(context_instance)
  File "/usr/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/usr/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python2.7/site-packages/django/template/base.py", line 988, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python2.7/site-packages/django/template/base.py", line 955, in render_annotated
    return self.render(context)
  File "/usr/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/usr/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python2.7/site-packages/django/template/base.py", line 988, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python2.7/site-packages/django/template/base.py", line 955, in render_annotated
    return self.render(context)
  File "/usr/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python2.7/site-packages/django/template/base.py", line 988, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python2.7/site-packages/django/template/base.py", line 955, in render_annotated
    return self.render(context)
  File "/usr/lib/python2.7/site-packages/django/template/library.py", line 201, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/usr/share/weblate/weblate/trans/templatetags/permissions.py", line 29, in can_translate
    user, translation
  File "/usr/share/weblate/weblate/trans/permissions.py", line 111, in wrapper
    target_object.permissions_cache[key] = func(user, target_object)
  File "/usr/share/weblate/weblate/trans/permissions.py", line 143, in can_translate
    return can_edit(user, translation, 'trans.save_translation')
  File "/usr/share/weblate/weblate/trans/permissions.py", line 124, in can_edit
    if check_owner(user, translation.subproject.project, permission):
  File "/usr/share/weblate/weblate/trans/permissions.py", line 38, in check_owner
    group = Group.objects.get(name='Owners')
  File "/usr/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 387, in get
    self.model._meta.object_name
DoesNotExist: Group matching query does not exist.
```

### Server configuration

Weblate version: `2.6`

**Comment by nijel** [comment]
Did the database migration run without problem? This group should be created during it...

**Comment by martinpucik** [comment]
Yeah, there were no issues with updating and migrating to new version. 

But I think I might break it by removing `Owners` group. Are there any other groups I should stop removing? 😄

**Comment by nijel** [comment]
Yes there are - all which are automatically created ;-) - Guests, Users, Owners and Managers. See https://docs.weblate.org/en/latest/admin/access.html

**Comment by nijel** [comment]
You can recreate it by:

```sh
./manage.py setupgroups
```

**Comment by desmax** [comment]
What if I have this one:
I think my migration process was interrupted(just a guess, I lost connection to server), then I ran makemigrations(since it was complaining and suggesting to do it) and  then I tried migrate again:
```./manage.py migrate
Operations to perform:
  Apply all migrations: accounts, admin, auth, authtoken, contenttypes, gitexport, lang, screenshots, sessions, sites, social_django, trans
Running migrations:
  No migrations to apply.
Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 224, in handle
    self.verbosity, self.interactive, connection.alias, apps=post_migrate_apps, plan=plan,
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/sql.py", line 53, in emit_post_migrate_signal
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/django/dispatch/dispatcher.py", line 191, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/srv/sites/wl/weblate/accounts/models.py", line 1093, in sync_create_groups
    create_groups(False)
  File "/srv/sites/wl/weblate/accounts/models.py", line 1013, in create_groups
    Permission.objects.get(codename='add_screenshot'),
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: Permission matching query does not exist.```

**Comment by nijel** [comment]
@desmax Probably wrong ordering of `INSTALLED_APPS`, `weblate.accounts` has to be after `weblate.screenshots`. I've changed this in 78aa271bb so that it does not depend on ordering of individual apps, only `weblate` has to be last.

If the problem persists, it's different issue, please open separate ticket for that.

**Comment by desmax** [comment]
@nijel Thanks, after a pull everything worked!

**Comment by Manishuystquwyy** [comment]
> ### Steps to reproduce
> 1. Change user group
> 2. Try to access component's language
> 3. Weblate throws Internal Server Error
> 
> ### Error stacktrace:
> ```python
> weblate[7174]: ERROR Internal Server Error: /translate/annie/app/ar/
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
>     response = self.process_exception_by_middleware(e, request)
>   File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/usr/share/weblate/weblate/trans/views/edit.py", line 598, in translate
>     'addword_form': InlineWordForm(),
>   File "/usr/share/weblate/weblate/trans/util.py", line 298, in render
>     return django_render(request, template, context, status=status)
>   File "/usr/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 53, in render
>     return HttpResponse(loader.render_to_string(*args, **kwargs),
>   File "/usr/lib/python2.7/site-packages/django/template/loader.py", line 114, in render_to_string
>     template_name, context, context_instance, dirs, dictionary)
>   File "/usr/lib/python2.7/site-packages/django/template/engine.py", line 244, in render_to_string
>     return t.render(context_instance)
>   File "/usr/lib/python2.7/site-packages/django/template/base.py", line 206, in render
>     return self._render(context)
>   File "/usr/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
>     return self.nodelist.render(context)
>   File "/usr/lib/python2.7/site-packages/django/template/base.py", line 988, in render
>     bit = node.render_annotated(context)
>   File "/usr/lib/python2.7/site-packages/django/template/base.py", line 955, in render_annotated
>     return self.render(context)
>   File "/usr/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
>     return compiled_parent._render(context)
>   File "/usr/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
>     return self.nodelist.render(context)
>   File "/usr/lib/python2.7/site-packages/django/template/base.py", line 988, in render
>     bit = node.render_annotated(context)
>   File "/usr/lib/python2.7/site-packages/django/template/base.py", line 955, in render_annotated
>     return self.render(context)
>   File "/usr/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
>     result = block.nodelist.render(context)
>   File "/usr/lib/python2.7/site-packages/django/template/base.py", line 988, in render
>     bit = node.render_annotated(context)
>   File "/usr/lib/python2.7/site-packages/django/template/base.py", line 955, in render_annotated
>     return self.render(context)
>   File "/usr/lib/python2.7/site-packages/django/template/library.py", line 201, in render
>     output = self.func(*resolved_args, **resolved_kwargs)
>   File "/usr/share/weblate/weblate/trans/templatetags/permissions.py", line 29, in can_translate
>     user, translation
>   File "/usr/share/weblate/weblate/trans/permissions.py", line 111, in wrapper
>     target_object.permissions_cache[key] = func(user, target_object)
>   File "/usr/share/weblate/weblate/trans/permissions.py", line 143, in can_translate
>     return can_edit(user, translation, 'trans.save_translation')
>   File "/usr/share/weblate/weblate/trans/permissions.py", line 124, in can_edit
>     if check_owner(user, translation.subproject.project, permission):
>   File "/usr/share/weblate/weblate/trans/permissions.py", line 38, in check_owner
>     group = Group.objects.get(name='Owners')
>   File "/usr/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
>     return getattr(self.get_queryset(), name)(*args, **kwargs)
>   File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 387, in get
>     self.model._meta.object_name
> DoesNotExist: Group matching query does not exist.
> ```
> 
> ### Server configuration
> Weblate version: `2.6`
3354-python/django_mkts$ python manage.py createsuperuser
The API clients available in this package are deprecated and will be no longer available in their current form starting with version 2.0!
Username: ram
Email address: py-manish@mobiloitte.com
Password: 
Password (again): 
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vinay.chaubey/Desktop/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/vinay.chaubey/Desktop/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vinay.chaubey/Desktop/env/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/vinay.chaubey/Desktop/env/lib/python3.5/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 63, in execute
    return super(Command, self).execute(*args, **options)
  File "/home/vinay.chaubey/Desktop/env/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/vinay.chaubey/Desktop/env/lib/python3.5/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 183, in handle
    self.UserModel._default_manager.db_manager(database).create_superuser(**user_data)
  File "/home/vinay.chaubey/Desktop/env/lib/python3.5/site-packages/django/contrib/auth/models.py", line 170, in create_superuser
    return self._create_user(username, email, password, **extra_fields)
  File "/home/vinay.chaubey/Desktop/env/lib/python3.5/site-packages/django/contrib/auth/models.py", line 153, in _create_user
    user.save(using=self._db)
  File "/home/vinay.chaubey/Desktop/env/lib/python3.5/site-packages/django/contrib/auth/base_user.py", line 80, in save
    super(AbstractBaseUser, self).save(*args, **kwargs)
  File "/home/vinay.chaubey/Desktop/env/lib/python3.5/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/vinay.chaubey/Desktop/env/lib/python3.5/site-packages/django/db/models/base.py", line 848, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "/home/vinay.chaubey/Desktop/env/lib/python3.5/site-packages/django/dispatch/dispatcher.py", line 193, in send
    for receiver in self._live_receivers(sender)
  File "/home/vinay.chaubey/Desktop/env/lib/python3.5/site-packages/django/dispatch/dispatcher.py", line 193, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/home/vinay.chaubey/Desktop/piattaformacryptoexchang-18093354-python/django_mkts/users/models.py", line 126, in add_defaults
    group = Group.objects.get(name='Trader')
  File "/home/vinay.chaubey/Desktop/env/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vinay.chaubey/Desktop/env/lib/python3.5/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: Group matching query does not exist.




please give me the solution.
the problem arrise when I change my database db.sqllite3 to postgress
how to solve this type of problem.

**Comment by nijel** [comment]
@Manishuystquwyy just run `./manage.py setupgroups` as mentioned before.

**Comment by elizabethadegbaju** [comment]
> 
> 
> @Manishuystquwyy just run `./manage.py setupgroups` as mentioned before.

this didn't work

**Comment by nijel** [comment]
@elizabethadegbaju You're probably hitting something different from this *three years* old issue. Please open separate issue for that or use our [support](https://weblate.org/support/).

**Comment by NanceCA** [comment]
> > @Manishuystquwyy just run `./manage.py setupgroups` as mentioned before.
> 
> this didn't work

hey there!! @elizabethadegbaju  did you end up finding a solution to this? I am having the same issue that I haven't been able to solve for a couple of days now. Same error: "django.contrib.auth.models.DoesNotExist: Group matching query does not exist."

**Comment by nijel** [comment]
Please report separate issue with all needed information (where do you get the error, what traceback does the error have, what version do you use,...). The related code has been completely rewritten since the original report, so it's not really useful to followup here.

**Comment by abcdeCoder** [comment]
> ```shell
> ./manage.py setupgroups
> ```

is this command valid for ubantu 22.4
