### ISSUE TITLE
Can't update project repository if a subproject's files are missing

### ISSUE THREAD

**Issue by stormi** [nijel/weblate#1096]
Hi,

Sorry by advance if the issue is already fixed, my weblate instance is an old 2.3.

I have a project with many subprojects, created with the ./manage.py command that allows to create subprojects automatically. 

For a test, I removed a directory that contains files for 2 different subprojects from my git repository then I tried to update the repository in weblate's web interface. It fails. Below is the trace received by mail.

```
Internal Server Error: /update/sam_oostats/
Traceback (most recent call last):
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/Django-1.7.8-py2.7.egg/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/Django-1.7.8-py2.7.egg/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/bitnami/apps/weblate/weblate/trans/views/git.py", line 140, in update_project
    return perform_update(request, obj)
  File "/opt/bitnami/apps/weblate/weblate/trans/views/git.py", line 75, in perform_update
    method=request.GET.get('method', None)
  File "/opt/bitnami/apps/weblate/weblate/trans/views/git.py", line 41, in execute_locked
    result = call(request, *args, **kwargs)
  File "/opt/bitnami/apps/weblate/weblate/trans/models/project.py", line 381, in do_update
    ret &= component.do_update(request, method=method)
  File "/opt/bitnami/apps/weblate/weblate/trans/models/subproject.py", line 662, in do_update
    self.create_translations(request=request)
  File "/opt/bitnami/apps/weblate/weblate/trans/models/subproject.py", line 942, in create_translations
    subproject.create_translations(force, langs, request=request)
  File "/opt/bitnami/apps/weblate/weblate/trans/models/subproject.py", line 921, in create_translations
    self, lang, code, path, force, request=request
  File "/opt/bitnami/apps/weblate/weblate/trans/models/translation.py", line 68, in check_sync
    translation.check_sync(force, request=request)
  File "/opt/bitnami/apps/weblate/weblate/trans/models/translation.py", line 470, in check_sync
    if self.revision != self.get_git_blob_hash():
  File "/opt/bitnami/apps/weblate/weblate/trans/models/translation.py", line 589, in get_git_blob_hash
    ret = self.repository.get_object_hash(self.get_filename())
  File "/opt/bitnami/apps/weblate/weblate/trans/vcs.py", line 558, in get_object_hash
    return self.execute(['ls-tree', 'HEAD', real_path]).split()[2]
IndexError: list index out of range
```

**Comment by nijel** [comment]
Yes, this is already fixed: #769
