### ISSUE TITLE
manage.py commit_pending: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 22: ordinal not in range(128)

### ISSUE THREAD

**Issue by nblock** [nijel/weblate#1110]
### Steps to reproduce
1. Make sure that translations are pending
2. Run: `./manage.py commit_pending --all --age=0`

### Actual behaviour
```
$ ./manage.py commit_pending --all --age=0
Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/weblate-venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/var/www/weblate-venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/weblate-venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/weblate-venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/var/www/weblate/weblate/trans/management/commands/commit_pending.py", line 56, in handle
    self.stdout.write('Committing %s' % translation)
  File "/var/www/weblate-venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 111, in write
    if ending and not msg.endswith(ending):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 22: ordinal not in range(128)
```

No pending changes are committed.

### Expected behaviour
Pending changes get committed.

### Server configuration
 * Weblate 2.6
 * Python 2.7.9
 * Django 1.8
 * six 1.9.0
 * python-social-auth 0.2.7
 * Translate Toolkit 1.14.0-rc1
 * Whoosh 2.7.0
 * Git 2.1.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.4.4
 * django-crispy-forms 1.4.0
 * compressor 1.5
 * djangorestframework 3.3.3
 * pytz 2015.2
 * pyuca N/A
 * pyLibravatar N/A
 * Mercurial 3.3.3
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment]
You can workaround it by passing ```-v 0```.

**Comment by nblock** [comment]
Great, thx for fixing it so quickly.
