### ISSUE TITLE
Migrate Script references Debian-Mysql-Library on Ubuntu

### ISSUE THREAD

**Issue by AWessel77** [nijel/weblate#1227]
### Steps to reproduce
1. Install Weblate on Ubuntu 16.04 LTS
2. Use MySql as Database and install platform specific python library.
Following the docs it should be 'python-pymysql' for ubuntu
3. run `./manage.py migrate` to fill the database with data

### Actual behaviour
The script moans that there is no 'mysqldb' module.
`django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module: No module named MySQLdb`

### Expected behaviour
It should be happy with the installed lib/module 'python-pymysql'.

### Server configuration
`./manage.py list_versions` would output the same error message like `./manage.py migrate` if I don't install 'python-mysqldb'. 
After installation of 'python-mysqldb' I get:
```
Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/dist-packages/social/apps/django_app/default/models.py", line 14, in <module>
    from social.apps.django_app.default.fields import JSONField
  File "/usr/lib/python2.7/dist-packages/social/apps/django_app/default/fields.py", line 14, in <module>
    class JSONField(six.with_metaclass(models.SubfieldBase, models.TextField)):
AttributeError: 'module' object has no attribute 'SubfieldBase'
```

**Comment by nijel** [comment]
The problem with Ubuntu, is that they ship patched Django to use on pymysql instead of mysqldb.  For Xenial (16.04) it seems that the pymysql should be the correct package as it is in Django package suggests: http://packages.ubuntu.com/xenial/python-django

Did you install Django from the Ubuntu package?

The last error is from incompatible python-social-auth with python-django.

**Comment by AWessel77** [comment]
> Did you install Django from the Ubuntu package?
Yes, I installed Django as an Ubuntu package.
