### ISSUE TITLE
Admin scripts are all failing after installation on Ubuntu

### ISSUE THREAD

**Issue by AWessel77** [nijel/weblate#1228]
### Steps to reproduce
1. Follow the installation instructions for Ubuntu. Use Ubuntu 16.04 LTS.
2. Install python-mysqldb to become rid of error message `django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module: No module named MySQLdb`
3. Execute any admin script like `./manage.py list_versions` or `./manage.py migrate`

### Actual behaviour
I get the error
```
Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/dist-packages/social/apps/django_app/default/models.py", line 14, in <module>
    from social.apps.django_app.default.fields import JSONField
  File "/usr/lib/python2.7/dist-packages/social/apps/django_app/default/fields.py", line 14, in <module>
    class JSONField(six.with_metaclass(models.SubfieldBase, models.TextField)):
AttributeError: 'module' object has no attribute 'SubfieldBase'
```

### Expected behaviour
Execution of the admin script.

### Server configuration
Please see section 'Actual behaviour' for the output of command `./manage.py list_versions`.

**Comment by nijel** [comment]
The error is from incompatible python-social-auth with python-django. Either use both packages from distribution or both from pypi, you currently seem to mix them (see also #1227).

**Comment by AWessel77** [comment]
Thank you for the quick reply.
I just started again the installation using only pip for the installation of the python requirements and now it works like intended.

**Comment by nijel** [comment]
The problem was that you're using new Django (installed by pip into /usr/local/lib/python2.7/dist-packages/django) with old python-social-auth (installed from packages).
