### ISSUE TITLE
GitHub auth: TypeError at /accounts/complete/github/

### ISSUE THREAD

**Issue by dtschan** [nijel/weblate#1263]
### Steps to reproduce
1. Install Weblate 2.8 or 2.9-dev
2. Configure GitHub authentication as documented here: https://docs.weblate.org/en/latest/admin/auth.html#github-authentication
3. Try to log into Weblate with your GitHub account.

### Actual behaviour

TypeError at /accounts/complete/github/

argument of type 'NoneType' is not iterable

Traceback:

```
File "/opt/app-root/src/.local/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
  39.             response = get_response(request)

File "/opt/app-root/src/.local/lib/python2.7/site-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/opt/app-root/src/.local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/opt/app-root/src/.local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/opt/app-root/src/.local/lib/python2.7/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  57.         response = view_func(request, *args, **kwargs)

File "/opt/app-root/src/.local/lib/python2.7/site-packages/django/views/decorators/csrf.py" in wrapped_view
  58.         return view_func(*args, **kwargs)

File "/opt/app-root/src/.local/lib/python2.7/site-packages/social/apps/django_app/utils.py" in wrapper
  51.             return func(request, backend, *args, **kwargs)

File "/opt/app-root/src/.local/lib/python2.7/site-packages/social/apps/django_app/views.py" in complete
  28.                        redirect_name=REDIRECT_FIELD_NAME, *args, **kwargs)

File "/opt/app-root/src/.local/lib/python2.7/site-packages/social/actions.py" in do_complete
  44.         user = backend.complete(user=user, *args, **kwargs)

File "/opt/app-root/src/.local/lib/python2.7/site-packages/social/backends/base.py" in complete
  41.         return self.auth_complete(*args, **kwargs)

File "/opt/app-root/src/.local/lib/python2.7/site-packages/social/utils.py" in wrapper
  246.             return func(*args, **kwargs)

File "/opt/app-root/src/.local/lib/python2.7/site-packages/social/backends/oauth.py" in auth_complete
  397.                             *args, **kwargs)

File "/opt/app-root/src/.local/lib/python2.7/site-packages/social/utils.py" in wrapper
  246.             return func(*args, **kwargs)

File "/opt/app-root/src/.local/lib/python2.7/site-packages/social/backends/oauth.py" in do_auth
  408.         return self.strategy.authenticate(*args, **kwargs)

File "/opt/app-root/src/.local/lib/python2.7/site-packages/social/strategies/django_strategy.py" in authenticate
  96.         return authenticate(*args, **kwargs)

File "/opt/app-root/src/.local/lib/python2.7/site-packages/django/contrib/auth/__init__.py" in authenticate
  74.             user = backend.authenticate(**credentials)

File "/opt/app-root/src/weblate/accounts/auth.py" in authenticate
  99.         if '@' in username:

Exception Type: TypeError at /accounts/complete/github/
Exception Value: argument of type 'NoneType' is not iterable
```
### Expected behaviour

Can login with my GitHub account.
### Server configuration

I tried:
- Installations of Weblate 2.8 and 2.9-dev based on nijel/weblate Docker image
- Own Docker image with gunicorn
- http and https
- Different callback URLs: http://domain.tld/, https://domain.tld/, http://domain.tld/accounts/complete/github/, https://domain.tld/accounts/complete/github/, http://domain.tld/complete/github/, https://domain.tld/complete/github/

However I always used the `settings.py` file from the official Docker image. None of these combinations worked. Sometimes I also saw this error: "AuthStateMissing: Session value state missing". None of the solutions you can find on Google for this message works.

python manage.py list_versions of own image with gunicorn:
- Weblate 2.9-dev
- Python 2.7.8
- Django 1.10.2
- six 1.10.0
- python-social-auth 0.2.21
- Translate Toolkit 2.0.0b6
- Whoosh 2.7.4
- defusedxml 0.4.1
- Git 1.8.3.1
- Pillow (PIL) 1.1.7
- dateutil 2.5.3
- lxml 3.6.4
- django-crispy-forms 1.6.1
- compressor 2.1
- djangorestframework 3.5.1
- Database backends: django.db.backends.postgresql_psycopg2

Any help is appreciated.
##

**Comment by nijel** [comment]
Callback should be `https://domain.tld/` (if you use https), but I don't think it's the problem here.

Anyway I've fixed the authentication to deal with None as username, you will probably get some more useful error message now.

**Comment by dtschan** [comment]
Thanks. Interestingly enough login now works and I see username, full name and email address from GitHub in the account tab. Just the avatar icon is missing and the log now shows the following exception. Could this be the original issue:

```
ERROR Internal Server Error: /avatar/32/dtschan.png
Traceback (most recent call last):
  File "/opt/app-root/src/.local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/opt/app-root/src/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/opt/app-root/src/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/app-root/src/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/app-root/src/weblate/accounts/views.py", line 375, in user_avatar
    content=get_avatar_image(request, user, size)
  File "/opt/app-root/src/weblate/accounts/avatar.py", line 135, in get_avatar_image
    image = download_avatar_image(user, size)
  File "/opt/app-root/src/weblate/accounts/avatar.py", line 157, in download_avatar_image
    url = avatar_for_email(user.email, size)
  File "/opt/app-root/src/weblate/accounts/avatar.py", line 86, in avatar_for_email
    urlencode(appsettings.AVATAR_DEFAULT_IMAGE),
  File "/opt/rh/python27/root/usr/lib64/python2.7/urllib.py", line 1318, in urlencode
    raise TypeError
TypeError: not a valid non-string sequence or mapping object
```

**Comment by dtschan** [comment]
Problem disappears when installing pyLibravatar. Also without commit a322438 the original issue no longer occurs when pyLibravatar is installed. So the above exception indeed seems to be the root cause.
