### ISSUE TITLE
UnicodeDecodeError when importing new components

### ISSUE THREAD

**Issue by mart-e** [nijel/weblate#1295]
### Steps to reproduce
1. Create new project
2. Add a new resource from .po file

### Actual behaviour
Crashing when processing the first file of the folder
```INFO myproj/mycompo: updating repository
INFO myproj/mycompo: update took 0.31 seconds:
INFO myproj/mycompo: merge remote into repo
INFO myproj/mycompo: updating repository
INFO myproj/mycompo: update took 0.25 seconds:
INFO myproj/mycompo: merge remote into repo
INFO myproj/mycompo: checking mycompo/af.po (af) [1/68]
INFO myproj/mycompo/af: processing mycompo/af.po, revision has changed
ERROR Internal Server Error: /admin/trans/subproject/add/
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.5/site-packages/django/contrib/admin/options.py", line 544, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/django/contrib/admin/sites.py", line 211, in inner
    return view(request, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/django/contrib/admin/options.py", line 1509, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/usr/lib/python3.5/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.5/site-packages/django/contrib/admin/options.py", line 1449, in changeform_view
    self.save_model(request, new_object, form, not add)
  File "/usr/lib/python3.5/site-packages/django/contrib/admin/options.py", line 1007, in save_model
    obj.save()
  File "/home/mat/other/weblate/weblate/trans/models/subproject.py", line 1403, in save
    self.create_translations()
  File "/home/mat/other/weblate/weblate/trans/models/subproject.py", line 1034, in create_translations
    self, lang, code, path, force, request=request
  File "/home/mat/other/weblate/weblate/trans/models/translation.py", line 78, in check_sync
    translation.check_sync(force, request=request)
  File "/home/mat/other/weblate/weblate/trans/models/translation.py", line 474, in check_sync
    self, unit, pos
  File "/home/mat/other/weblate/weblate/trans/models/unit.py", line 109, in update_from_unit
    dbunit.update_from_unit(unit, pos, created)
  File "/home/mat/other/weblate/weblate/trans/models/unit.py", line 497, in update_from_unit
    same_state=same_state
  File "/home/mat/other/weblate/weblate/trans/models/unit.py", line 767, in save
    update_index_unit(self, force_insert)
  File "/home/mat/other/weblate/weblate/trans/search.py", line 238, in update_index_unit
    update_source_unit_index(writer, unit)
  File "/usr/lib/python3.5/site-packages/whoosh/writing.py", line 210, in __exit__
    self.commit()
  File "/usr/lib/python3.5/site-packages/whoosh/writing.py", line 1037, in commit
    self.writer.commit(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/whoosh/writing.py", line 922, in commit
    finalsegments = self._merge_segments(mergetype, optimize, merge)
  File "/usr/lib/python3.5/site-packages/whoosh/writing.py", line 827, in _merge_segments
    return mergetype(self, self.segments)
  File "/usr/lib/python3.5/site-packages/whoosh/writing.py", line 101, in MERGE_SMALL
    writer.add_reader(reader)
  File "/usr/lib/python3.5/site-packages/whoosh/writing.py", line 710, in add_reader
    self.add_postings_to_pool(reader, basedoc, docmap)
  File "/usr/lib/python3.5/site-packages/whoosh/writing.py", line 647, in add_postings_to_pool
    for item in items:
  File "/usr/lib/python3.5/site-packages/whoosh/writing.py", line 583, in _process_posts
    for fieldname, text, docnum, weight, vbytes in items:
  File "/usr/lib/python3.5/site-packages/whoosh/reading.py", line 429, in iter_postings
    yield (fieldname, btext, m.id(), m.weight(), m.value())
  File "/usr/lib/python3.5/site-packages/whoosh/codec/whoosh3.py", line 980, in id
    self._read_ids()
  File "/usr/lib/python3.5/site-packages/whoosh/codec/whoosh3.py", line 1082, in _read_ids
    self._read_data()
  File "/usr/lib/python3.5/site-packages/whoosh/codec/whoosh3.py", line 1077, in _read_data
    self._data = loads(b)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 4: ordinal not in range(128)
Internal Server Error: /admin/trans/subproject/add/
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.5/site-packages/django/contrib/admin/options.py", line 544, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/django/contrib/admin/sites.py", line 211, in inner
    return view(request, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/django/contrib/admin/options.py", line 1509, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/usr/lib/python3.5/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.5/site-packages/django/contrib/admin/options.py", line 1449, in changeform_view
    self.save_model(request, new_object, form, not add)
  File "/usr/lib/python3.5/site-packages/django/contrib/admin/options.py", line 1007, in save_model
    obj.save()
  File "/home/mat/other/weblate/weblate/trans/models/subproject.py", line 1403, in save
    self.create_translations()
  File "/home/mat/other/weblate/weblate/trans/models/subproject.py", line 1034, in create_translations
    self, lang, code, path, force, request=request
  File "/home/mat/other/weblate/weblate/trans/models/translation.py", line 78, in check_sync
    translation.check_sync(force, request=request)
  File "/home/mat/other/weblate/weblate/trans/models/translation.py", line 474, in check_sync
    self, unit, pos
  File "/home/mat/other/weblate/weblate/trans/models/unit.py", line 109, in update_from_unit
    dbunit.update_from_unit(unit, pos, created)
  File "/home/mat/other/weblate/weblate/trans/models/unit.py", line 497, in update_from_unit
    same_state=same_state
  File "/home/mat/other/weblate/weblate/trans/models/unit.py", line 767, in save
    update_index_unit(self, force_insert)
  File "/home/mat/other/weblate/weblate/trans/search.py", line 238, in update_index_unit
    update_source_unit_index(writer, unit)
  File "/usr/lib/python3.5/site-packages/whoosh/writing.py", line 210, in __exit__
    self.commit()
  File "/usr/lib/python3.5/site-packages/whoosh/writing.py", line 1037, in commit
    self.writer.commit(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/whoosh/writing.py", line 922, in commit
    finalsegments = self._merge_segments(mergetype, optimize, merge)
  File "/usr/lib/python3.5/site-packages/whoosh/writing.py", line 827, in _merge_segments
    return mergetype(self, self.segments)
  File "/usr/lib/python3.5/site-packages/whoosh/writing.py", line 101, in MERGE_SMALL
    writer.add_reader(reader)
  File "/usr/lib/python3.5/site-packages/whoosh/writing.py", line 710, in add_reader
    self.add_postings_to_pool(reader, basedoc, docmap)
  File "/usr/lib/python3.5/site-packages/whoosh/writing.py", line 647, in add_postings_to_pool
    for item in items:
  File "/usr/lib/python3.5/site-packages/whoosh/writing.py", line 583, in _process_posts
    for fieldname, text, docnum, weight, vbytes in items:
  File "/usr/lib/python3.5/site-packages/whoosh/reading.py", line 429, in iter_postings
    yield (fieldname, btext, m.id(), m.weight(), m.value())
  File "/usr/lib/python3.5/site-packages/whoosh/codec/whoosh3.py", line 980, in id
    self._read_ids()
  File "/usr/lib/python3.5/site-packages/whoosh/codec/whoosh3.py", line 1082, in _read_ids
    self._read_data()
  File "/usr/lib/python3.5/site-packages/whoosh/codec/whoosh3.py", line 1077, in _read_data
    self._data = loads(b)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 4: ordinal not in range(128)
[07/Dec/2016 13:41:15] "POST /admin/trans/subproject/add/ HTTP/1.1" 500 242933
```

### Server configuration
```
$ python --version
Python 3.5.2
$ python manage.py list_versions
 * Weblate weblate-2.9-201-g8b2af9a
 * Python 3.5.2
 * Django 1.10.3
 * six 1.10.0
 * python-social-auth 0.2.21
 * Translate Toolkit 2.0.0b7
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 2.10.2
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.0
 * lxml 3.6.4
 * django-crispy-forms 1.6.1
 * compressor 2.1
 * djangorestframework 3.5.3
 * git-svn 2.10.2
 * Database backends: django.db.backends.postgresql
$ postgres --version
postgres (PostgreSQL) 9.6.1
$ psql --list | grep weblate
 weblate   | postgres | UTF8     | en_GB.UTF-8 | en_GB.UTF-8 | 
```

I checked at the `Unit.objects.update_from_unit(self, unit, pos)` and `unit.get_source()` indicates it is the first term (which have no translation in af.po btw).

Thanks

**Comment by nijel** [comment]
Looks like a Whoosh bug on Python 3, see https://github.com/nijel/weblate/issues/1075 and https://bitbucket.org/mchaput/whoosh/issues/441/unicodedecodeerror-on-search

**Comment by mart-e** [comment]
Indeed it seems to work on python2.
Thanks for the info and let's hope it will be fixed.
