### ISSUE TITLE
ProgrammingError: column "enable_hooks" of relation "trans_project" already exists

### ISSUE THREAD

**Issue by nblock** [nijel/weblate#638]
Hi,
I tried to update a 2.0 instance on Debian Wheezy to 2.1 using the following steps:
* Unpack weblate-2.1.
* Copy existing weblate/settings.py and weblate/repos into the new weblate directory.
* Update the configuration from settings_example.py.
* Update requirements using pip.
* $ ./manage.py syncdb
```
Operations to perform:
  Synchronize unmigrated apps: sitemaps, weblate, crispy_forms
  Apply all migrations: lang, sessions, admin, sites, auth, default, contenttypes, accounts, trans
Synchronizing apps without migrations:
  Creating tables...
  Installing custom SQL...
  Installing indexes...
Running migrations:
  Applying trans.0002_auto_20141021_1347...Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/weblate-venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/var/www/weblate-venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/weblate-venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/var/www/weblate-venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/var/www/weblate-venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 533, in handle
    return self.handle_noargs(**options)
  File "/var/www/weblate-venv/local/lib/python2.7/site-packages/django/core/management/commands/syncdb.py", line 27, in handle_noargs
    call_command("migrate", **options)
  File "/var/www/weblate-venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 115, in call_command
    return klass.execute(*args, **defaults)
  File "/var/www/weblate-venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/var/www/weblate-venv/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 160, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/var/www/weblate-venv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 63, in migrate
    self.apply_migration(migration, fake=fake)
  File "/var/www/weblate-venv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 97, in apply_migration
    migration.apply(project_state, schema_editor)
  File "/var/www/weblate-venv/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 107, in apply
    operation.database_forwards(self.app_label, schema_editor, project_state, new_state)
  File "/var/www/weblate-venv/local/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 37, in database_forwards
    field,
  File "/var/www/weblate-venv/local/lib/python2.7/site-packages/django/db/backends/schema.py", line 390, in add_field
    self.execute(sql, params)
  File "/var/www/weblate-venv/local/lib/python2.7/site-packages/django/db/backends/schema.py", line 99, in execute
    cursor.execute(sql, params)
  File "/var/www/weblate-venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/var/www/weblate-venv/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/var/www/weblate-venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "enable_hooks" of relation "trans_project" already exists
```

Is there anything I'm missing here?

**Comment by nblock** [comment]
I re-installed my weblate installation and the issue is now gone. I was bitten by several other things too, so re-installing was the easy way out.
