### ISSUE TITLE
First name should support unicode

### ISSUE THREAD

**Issue by paulpach** [nijel/weblate#661]
I am getting this exception when a user tries to commit:
```
 ERROR block-story/items: failed to update repository: abort: no suitable response from remote hg! (255)
[Tue Feb 24 08:57:58 2015] [error] ERROR:weblate:block-story/items: failed to update repository: abort: no suitable response from remote hg! (255)
[Tue Feb 24 08:58:00 2015] [error] INFO block-story/items/pt: commiting pt/Items.po as Maria In\xc3\xaas Branco Gon\xc3\xa7alves <inesgoncalves@live.com>
[Tue Feb 24 08:58:00 2015] [error] INFO:weblate:block-story/items/pt: commiting pt/Items.po as Maria In\xc3\xaas Branco Gon\xc3\xa7alves <inesgoncalves@live.com>
[Tue Feb 24 08:58:01 2015] [error] ERROR Internal Server Error: /update/block-story/items/es/
[Tue Feb 24 08:58:01 2015] [error] Traceback (most recent call last):
[Tue Feb 24 08:58:01 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/python/virtenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
[Tue Feb 24 08:58:01 2015] [error]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Tue Feb 24 08:58:01 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/python/virtenv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
[Tue Feb 24 08:58:01 2015] [error]     return view_func(request, *args, **kwargs)
[Tue Feb 24 08:58:01 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/python/virtenv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
[Tue Feb 24 08:58:01 2015] [error]     return view_func(request, *args, **kwargs)
[Tue Feb 24 08:58:01 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/app-root/runtime/repo/weblate/trans/views/git.py", line 143, in update_translation
[Tue Feb 24 08:58:01 2015] [error]     return perform_update(request, obj)
[Tue Feb 24 08:58:01 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/app-root/runtime/repo/weblate/trans/views/git.py", line 70, in perform_update
[Tue Feb 24 08:58:01 2015] [error]     method=request.GET.get('method', None)
[Tue Feb 24 08:58:01 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/app-root/runtime/repo/weblate/trans/views/git.py", line 36, in execute_locked
[Tue Feb 24 08:58:01 2015] [error]     result = call(request, *args, **kwargs)
[Tue Feb 24 08:58:01 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/app-root/runtime/repo/weblate/trans/models/translation.py", line 568, in do_update
[Tue Feb 24 08:58:01 2015] [error]     return self.subproject.do_update(request, method=method)
[Tue Feb 24 08:58:01 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/app-root/runtime/repo/weblate/trans/models/subproject.py", line 623, in do_update
[Tue Feb 24 08:58:01 2015] [error]     self.commit_pending(request)
[Tue Feb 24 08:58:01 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/app-root/runtime/repo/weblate/trans/models/subproject.py", line 746, in commit_pending
[Tue Feb 24 08:58:01 2015] [error]     translation.commit_pending(request, skip_push=skip_push)
[Tue Feb 24 08:58:01 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/app-root/runtime/repo/weblate/trans/models/translation.py", line 699, in commit_pending
[Tue Feb 24 08:58:01 2015] [error]     request, last, self.last_change, True, True, skip_push
[Tue Feb 24 08:58:01 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/app-root/runtime/repo/weblate/trans/models/translation.py", line 831, in git_commit
[Tue Feb 24 08:58:01 2015] [error]     self.__git_commit(author, timestamp, sync)
[Tue Feb 24 08:58:01 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/app-root/runtime/repo/weblate/trans/models/translation.py", line 782, in __git_commit
[Tue Feb 24 08:58:01 2015] [error]     msg, author, timestamp, files
[Tue Feb 24 08:58:01 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/app-root/runtime/repo/weblate/trans/vcs.py", line 871, in commit
[Tue Feb 24 08:58:01 2015] [error]     self.execute(cmd)
[Tue Feb 24 08:58:01 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/app-root/runtime/repo/weblate/trans/vcs.py", line 154, in execute
[Tue Feb 24 08:58:01 2015] [error]     self.last_output = self._popen(args, self.path)
[Tue Feb 24 08:58:01 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/app-root/runtime/repo/weblate/trans/vcs.py", line 147, in _popen
[Tue Feb 24 08:58:01 2015] [error]     raise RepositoryException(retcode, output_err, output)
[Tue Feb 24 08:58:01 2015] [error] RepositoryException: transaction abort!
[Tue Feb 24 08:58:01 2015] [error] rollback completed
[Tue Feb 24 08:58:01 2015] [error] abort: decoding near 'Maria In\xef\xbf\xbd\xef\xbf\xbds Branco': 'ascii' codec can't decode byte 0xc3 in position 8: ordinal not in range(128)! (255)
[Tue Feb 24 08:58:01 2015] [error] ERROR:django.request:Internal Server Error: /update/block-story/items/es/
[Tue Feb 24 08:58:01 2015] [error] Traceback (most recent call last):
[Tue Feb 24 08:58:01 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/python/virtenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
[Tue Feb 24 08:58:01 2015] [error]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Tue Feb 24 08:58:01 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/python/virtenv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
[Tue Feb 24 08:58:01 2015] [error]     return view_func(request, *args, **kwargs)
[Tue Feb 24 08:58:01 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/python/virtenv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
[Tue Feb 24 08:58:01 2015] [error]     return view_func(request, *args, **kwargs)
[Tue Feb 24 08:58:01 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/app-root/runtime/repo/weblate/trans/views/git.py", line 143, in update_translation
[Tue Feb 24 08:58:01 2015] [error]     return perform_update(request, obj)
[Tue Feb 24 08:58:01 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/app-root/runtime/repo/weblate/trans/views/git.py", line 70, in perform_update
[Tue Feb 24 08:58:01 2015] [error]     method=request.GET.get('method', None)
[Tue Feb 24 08:58:01 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/app-root/runtime/repo/weblate/trans/views/git.py", line 36, in execute_locked
[Tue Feb 24 08:58:01 2015] [error]     result = call(request, *args, **kwargs)
[Tue Feb 24 08:58:01 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/app-root/runtime/repo/weblate/trans/models/translation.py", line 568, in do_update
[Tue Feb 24 08:58:01 2015] [error]     return self.subproject.do_update(request, method=method)
[Tue Feb 24 08:58:01 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/app-root/runtime/repo/weblate/trans/models/subproject.py", line 623, in do_update
[Tue Feb 24 08:58:01 2015] [error]     self.commit_pending(request)
[Tue Feb 24 08:58:01 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/app-root/runtime/repo/weblate/trans/models/subproject.py", line 746, in commit_pending
[Tue Feb 24 08:58:01 2015] [error]     translation.commit_pending(request, skip_push=skip_push)
[Tue Feb 24 08:58:01 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/app-root/runtime/repo/weblate/trans/models/translation.py", line 699, in commit_pending
[Tue Feb 24 08:58:01 2015] [error]     request, last, self.last_change, True, True, skip_push
[Tue Feb 24 08:58:01 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/app-root/runtime/repo/weblate/trans/models/translation.py", line 831, in git_commit
[Tue Feb 24 08:58:01 2015] [error]     self.__git_commit(author, timestamp, sync)
[Tue Feb 24 08:58:01 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/app-root/runtime/repo/weblate/trans/models/translation.py", line 782, in __git_commit
[Tue Feb 24 08:58:01 2015] [error]     msg, author, timestamp, files
[Tue Feb 24 08:58:01 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/app-root/runtime/repo/weblate/trans/vcs.py", line 871, in commit
[Tue Feb 24 08:58:01 2015] [error]     self.execute(cmd)
[Tue Feb 24 08:58:01 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/app-root/runtime/repo/weblate/trans/vcs.py", line 154, in execute
[Tue Feb 24 08:58:01 2015] [error]     self.last_output = self._popen(args, self.path)
[Tue Feb 24 08:58:01 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/app-root/runtime/repo/weblate/trans/vcs.py", line 147, in _popen
[Tue Feb 24 08:58:01 2015] [error]     raise RepositoryException(retcode, output_err, output)
[Tue Feb 24 08:58:01 2015] [error] RepositoryException: transaction abort!
[Tue Feb 24 08:58:01 2015] [error] rollback completed
[Tue Feb 24 08:58:01 2015] [error] abort: decoding near 'Maria In\xef\xbf\xbd\xef\xbf\xbds Branco': 'ascii' codec can't decode byte 0xc3 in position 8: ordinal not in range(128)! (255)
144.9.40.131 - - [24/Feb/2015:08:56:45 -0500] "GET /update/block-story/items/es/?method=rebase HTTP/1.1" 500 6621 "http://weblate-blockstory.rhcloud.com/projects/block-story/items/es/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36"
- - - [24/Feb/2015:08:58:01 -0500] "OPTIONS * HTTP
```

In the first name,  the user entered  "... Inês ..."

**Comment by nijel** [comment]
Hmm strange that it works fine on hosted.weblate.org, but I'll look deeper into this later.

**Comment by paulpach** [comment]
Looking at the code,  it looks like this is a mercurial issue.  You are probably using git in hosted.weblate.org

**Comment by nijel** [comment]
I'm using both Git and Mercurial there. But the problem is in error handling, I've just fixed that. But the root cause is that you get the error and I'm curious what error is that :-).

**Comment by paulpach** [comment]
Ok,  I'll try again
