### ISSUE TITLE
Problem with GIT repository

### ISSUE THREAD

**Issue by evfool** [nijel/weblate#673]
Currently I can not commit nor check the repository maintenance from the user interface, the logged exception is:

```
ERROR:django.request:Internal Server Error: /js/git/tracking-live-core/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/www/weblate-2.1/weblate/trans/views/js.py", line 139, in git_status_project
    'object': obj,
  File "/usr/local/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 53, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "/usr/local/lib/python2.7/site-packages/django/template/loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 854, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 504, in render
    six.iteritems(self.extra_context)])
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 585, in resolve
    obj = self.var.resolve(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 735, in resolve
    value = self._resolve_lookup(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 789, in _resolve_lookup
    current = current()
  File "/usr/local/www/weblate-2.1/weblate/trans/models/project.py", line 341, in git_needs_commit
    if component.git_needs_commit():
  File "/usr/local/www/weblate-2.1/weblate/trans/models/subproject.py", line 1183, in git_needs_commit
    return self.repository.needs_commit()
  File "/usr/local/www/weblate-2.1/weblate/trans/models/subproject.py", line 476, in repository
    self._repository = VCS_REGISTRY[self.vcs](self.get_path())
KeyError: u'git'
```

**Comment by nijel** [comment]
Is git installed and working on that system?

**Comment by evfool** [comment]
Strangely yes, it did work so far, can't tell what happened:
* i've tried ./manage updategit, checkgit, both worked, but on the UI I still had internal server error
* after restarting uwsgi, the problem went away

**Comment by nijel** [comment]
At time weblate is loaded (so at uwsgi start) it checks for supported VCSs and if the git command is not working, it does not initialize it's backend, that's what has happened here...

**Comment by evfool** [comment]
uwsgi has been started some time ago, and the error has appeared first on a working server, while translating, so it seems strange, but I'm ok to leave this closed, as an uwsgi restart resolved it.
