### ISSUE TITLE
Google OpenId deprecated, oAuth2 not working

### ISSUE THREAD

**Issue by phw** [nijel/weblate#683]
The default Google OpenID provider in Weblate 2.2 stopped working on new hosts since Google deprecated OpenID and does not provide it for new hosts.

I tried following the Python Social Auth documentation to setup Google oAuth 2 (see http://psa.matiasaguirre.net/docs/backends/google.html), but it does only work partially. My configuration:

```
AUTHENTICATION_BACKENDS = ('social.backends.google.GoogleOAuth2', 'social.backends.email.EmailAuth', 'weblate.accounts.auth.WeblateUserBackend')
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = 'My Client ID'  ###
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'My Client Secret'  ###
```

The authentication process can be started (I have a button labeled "google-oauth2" in weblate, not pretty but would do the job), I see the Google consent screen, but upon redirection back to weblate the server fails with the following error message:

```
Internal Server Error: /accounts/complete/google-oauth2/
Traceback (most recent call last):
  File "/var/lib/openshift/5513fe21fcf933bd31000027/python/virtenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/openshift/5513fe21fcf933bd31000027/python/virtenv/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/var/lib/openshift/5513fe21fcf933bd31000027/python/virtenv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/openshift/5513fe21fcf933bd31000027/python/virtenv/lib/python2.7/site-packages/social/apps/django_app/utils.py", line 52, in wrapper
    return func(request, backend, *args, **kwargs)
  File "/var/lib/openshift/5513fe21fcf933bd31000027/python/virtenv/lib/python2.7/site-packages/social/apps/django_app/views.py", line 28, in complete
    redirect_name=REDIRECT_FIELD_NAME, *args, **kwargs)
  File "/var/lib/openshift/5513fe21fcf933bd31000027/python/virtenv/lib/python2.7/site-packages/social/actions.py", line 40, in do_complete
    user = backend.complete(user=user, *args, **kwargs)
  File "/var/lib/openshift/5513fe21fcf933bd31000027/python/virtenv/lib/python2.7/site-packages/social/backends/base.py", line 40, in complete
    return self.auth_complete(*args, **kwargs)
  File "/var/lib/openshift/5513fe21fcf933bd31000027/python/virtenv/lib/python2.7/site-packages/social/backends/oauth.py", line 379, in auth_complete
    *args, **kwargs)
  File "/var/lib/openshift/5513fe21fcf933bd31000027/python/virtenv/lib/python2.7/site-packages/social/backends/oauth.py", line 383, in do_auth
    data = self.user_data(access_token, *args, **kwargs)
  File "/var/lib/openshift/5513fe21fcf933bd31000027/python/virtenv/lib/python2.7/site-packages/social/backends/google.py", line 74, in user_data
    'alt': 'json'
  File "/var/lib/openshift/5513fe21fcf933bd31000027/python/virtenv/lib/python2.7/site-packages/social/backends/base.py", line 228, in get_json
    return self.request(url, *args, **kwargs).json()
  File "/var/lib/openshift/5513fe21fcf933bd31000027/python/virtenv/lib/python2.7/site-packages/social/backends/base.py", line 224, in request
    response.raise_for_status()
  File "/var/lib/openshift/5513fe21fcf933bd31000027/python/virtenv/lib/python2.7/site-packages/requests/models.py", line 834, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 403 Client Error: Forbidden

Request repr(): 
<WSGIRequest
path:/accounts/complete/google-oauth2/,
GET:<QueryDict: {u'num_sessions': [u'3'], u'code': [u'4/yn2LPjPSq7uKUvPpQ6O-QntAU2d_4dy0YDHG5CViuMw.EvOleB5fDo0Yyjz_MlCJoi0C69m0mAI'], u'prompt': [u'consent'], u'session_state': [u'4c5a277f8c0f83f0a1ebb1b782b227fce5e86333..3c87'], u'state': [u'XSkDC7zF9jziT6QxIIvvmjrZxWDxuBJp'], u'authuser': [u'0']}>,
POST:<QueryDict: {}>,
...
```

Is there some special support in Weblate required for this to work?

**Comment by nijel** [comment]
You need to enable Google+ API to make it work, see http://stackoverflow.com/questions/24377506/httperror-403-forbidden-with-django-and-python-social-auth-connecting-to-googl

**Comment by nijel** [comment]
I've updated documentation to cover that: https://docs.weblate.org/en/latest/admin/auth.html#google-oauth2

Also Google OAuth2 now shows nice text with icon on button, you can see it on https://demo.weblate.org/accounts/login/

**Comment by phw** [comment]
Thanks a lot for this lightning fast reply, works as expected now. Looking forward to see the nice icon once I update the server. But I guess I will probably wait for Weblate 2.3 to be released :)

**Comment by nijel** [comment]
Weblate 2.3 should be out somewhere in April, but definitely after Django 1.8 will be released as I want to ensure everything works with it. Generally the version from Git should be safe to run in production. Hosted Weblate <https://hosted.weblate.org/> runs it for most of the time.
