### ISSUE TITLE
Something went wrong during changing of site name

### ISSUE THREAD

**Issue by WTThomas** [nijel/weblate#689]
Hi,
What I've done in the admin-gui:
* deleted example.com 
* created another one which matches my domain / subdomain

Unfortunately something went wrong during this process.

Now I get an "Server Error-Message" when I try to open the Weblate-GUI :(

![weblate - google chrome_2015-03-31_17-46-03](https://cloud.githubusercontent.com/assets/3327272/6922785/e8262cc0-d7cd-11e4-97ad-1fa8506ed112.png)

My config file says this:
```
DoesNotExist: Site matching query does not exist.
ERROR Internal Server Error: /
Traceback (most recent call last):
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/bitnami/apps/weblate/weblate/trans/views/basic.py", line 104, in home
    'whiteboard_messages': wb_messages,
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 49, in render
    context_instance = RequestContext(request, current_app=current_app)
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/django/template/context.py", line 169, in __init__
    self.update(processor(request))
  File "/opt/bitnami/apps/weblate/weblate/trans/context_processors.py", line 60, in weblate_context
    'site_url': get_site_url(),
  File "/opt/bitnami/apps/weblate/weblate/trans/util.py", line 72, in get_site_url
    site = Site.objects.get_current()
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/django/contrib/sites/models.py", line 47, in get_current
    current_site = self.get(pk=sid)
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/django/db/models/query.py", line 310, in get
    self.model._meta.object_name)
DoesNotExist: Site matching query does not exist.
ERROR Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/django/core/handlers/base.py", line 150, in get_response
    response = callback(request, **param_dict)
  File "/opt/bitnami/apps/weblate/weblate/trans/views/basic.py", line 356, in not_found
    status=404
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 49, in render
    context_instance = RequestContext(request, current_app=current_app)
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/django/template/context.py", line 169, in __init__
    self.update(processor(request))
  File "/opt/bitnami/apps/weblate/weblate/trans/context_processors.py", line 60, in weblate_context
    'site_url': get_site_url(),
  File "/opt/bitnami/apps/weblate/weblate/trans/util.py", line 72, in get_site_url
    site = Site.objects.get_current()
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/django/contrib/sites/models.py", line 47, in get_current
    current_site = self.get(pk=sid)
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/django/db/models/query.py", line 310, in get
    self.model._meta.object_name)
DoesNotExist: Site matching query does not exist.
```

Is it possible that there is a bug?
If not, maybe you could give me a hint what's wrong here and how I can fix this.

Regards 
Tom

**Comment by nijel** [comment]
Probably by deleting the entry and creating new one, you have changed ID, so you should probably set the SITE_ID configuration to the same value, see https://docs.djangoproject.com/en/1.7/ref/settings/#std:setting-SITE_ID

**Comment by WTThomas** [comment]
Thanks nijel! :-)

That was the problem.
Changed the value from
````
SITE_ID = 1
````
to
````
SITE_ID = 2
````
and it works again!

Regards
Tom
