### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by ilijamt** [nijel/weblate#698]
I get this when I try to translate something with PHP strings, the setup is with a base English file.

Before I submit a translation I can see the strings that need to be translated, and everything works OK, but after submitting the first translation, I get this error.

If I check the files directly on the server I can see that the translation was submitted, and it's present in the PHP file.

Weblate 2.2

```
Internal Server Error: /projects/whmcs/main/mk/translate/
Traceback (most recent call last):
  File "/home/weblate/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/weblate/weblate/weblate/trans/views/edit.py", line 470, in translate
    user_locked = translation.is_user_locked(request)
  File "/home/weblate/weblate/weblate/trans/models/translation.py", line 296, in is_user_locked
    elif self.lock_time < datetime.now():
TypeError: can't compare offset-naive and offset-aware datetimes
```

**Comment by ilijamt** [comment]
I checked out the trunk version of the application and this works now, no issue.
