### ISSUE TITLE
Search gives internal error

### ISSUE THREAD

**Issue by paulpach** [nijel/weblate#713]
When I try to search,  I get an internal server error,  here is the log error:

```
[Wed Apr 15 14:04:23 2015] [error] Traceback (most recent call last):
[Wed Apr 15 14:04:23 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/python/virtenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
[Wed Apr 15 14:04:23 2015] [error]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Wed Apr 15 14:04:23 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/app-root/runtime/repo/weblate/trans/views/basic.py", line 121, in search
[Wed Apr 15 14:04:23 2015] [error]     search_form.cleaned_data,
[Wed Apr 15 14:04:23 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/app-root/runtime/repo/weblate/trans/models/unit.py", line 229, in search
[Wed Apr 15 14:04:23 2015] [error]     params
[Wed Apr 15 14:04:23 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/app-root/runtime/repo/weblate/trans/search.py", line 232, in fulltext_search
[Wed Apr 15 14:04:23 2015] [error]     index = get_source_index()
[Wed Apr 15 14:04:23 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/app-root/runtime/repo/weblate/trans/search.py", line 108, in get_source_index
[Wed Apr 15 14:04:23 2015] [error]     if not STORAGE.index_exists('source'):
[Wed Apr 15 14:04:23 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/python/virtenv/lib/python2.7/site-packages/whoosh/filedb/filestore.py", line 189, in index_exists
[Wed Apr 15 14:04:23 2015] [error]     ix = self.open_index(indexname)
[Wed Apr 15 14:04:23 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/python/virtenv/lib/python2.7/site-packages/whoosh/filedb/filestore.py", line 176, in open_index
[Wed Apr 15 14:04:23 2015] [error]     return indexclass(self, schema=schema, indexname=indexname)
[Wed Apr 15 14:04:23 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/python/virtenv/lib/python2.7/site-packages/whoosh/index.py", line 421, in __init__
[Wed Apr 15 14:04:23 2015] [error]     TOC.read(self.storage, self.indexname, schema=self._schema)
[Wed Apr 15 14:04:23 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/python/virtenv/lib/python2.7/site-packages/whoosh/index.py", line 632, in read
[Wed Apr 15 14:04:23 2015] [error]     check_size("int", _INT_SIZE)
[Wed Apr 15 14:04:23 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/python/virtenv/lib/python2.7/site-packages/whoosh/index.py", line 626, in check_size
[Wed Apr 15 14:04:23 2015] [error]     sz = stream.read_varint()
[Wed Apr 15 14:04:23 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/python/virtenv/lib/python2.7/site-packages/whoosh/filedb/structfile.py", line 191, in r
ead_varint
[Wed Apr 15 14:04:23 2015] [error]     return read_varint(self.read)
[Wed Apr 15 14:04:23 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/python/virtenv/lib/python2.7/site-packages/whoosh/util/varints.py", line 102, in read_varint
[Wed Apr 15 14:04:23 2015] [error]     b = ord(readfn(1))
[Wed Apr 15 14:04:23 2015] [error] TypeError: ord() expected a character, but string of length 0 found
[Wed Apr 15 14:04:23 2015] [error] ERROR:django.request:Internal Server Error: /search/
[Wed Apr 15 14:04:23 2015] [error] Traceback (most recent call last):
[Wed Apr 15 14:04:23 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/python/virtenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
[Wed Apr 15 14:04:23 2015] [error]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Wed Apr 15 14:04:23 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/app-root/runtime/repo/weblate/trans/views/basic.py", line 121, in search
[Wed Apr 15 14:04:23 2015] [error]     search_form.cleaned_data,
[Wed Apr 15 14:04:23 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/app-root/runtime/repo/weblate/trans/models/unit.py", line 229, in search
[Wed Apr 15 14:04:23 2015] [error]     params
[Wed Apr 15 14:04:23 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/app-root/runtime/repo/weblate/trans/search.py", line 232, in fulltext_search
[Wed Apr 15 14:04:23 2015] [error]     index = get_source_index()
[Wed Apr 15 14:04:23 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/app-root/runtime/repo/weblate/trans/search.py", line 108, in get_source_index
[Wed Apr 15 14:04:23 2015] [error]     if not STORAGE.index_exists('source'):
[Wed Apr 15 14:04:23 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/python/virtenv/lib/python2.7/site-packages/whoosh/filedb/filestore.py", line 189, in index_exists
[Wed Apr 15 14:04:23 2015] [error]     ix = self.open_index(indexname)
[Wed Apr 15 14:04:23 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/python/virtenv/lib/python2.7/site-packages/whoosh/filedb/filestore.py", line 176, in open_index
[Wed Apr 15 14:04:23 2015] [error]     return indexclass(self, schema=schema, indexname=indexname)
[Wed Apr 15 14:04:23 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/python/virtenv/lib/python2.7/site-packages/whoosh/index.py", line 421, in __init__
[Wed Apr 15 14:04:23 2015] [error]     TOC.read(self.storage, self.indexname, schema=self._schema)
[Wed Apr 15 14:04:23 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/python/virtenv/lib/python2.7/site-packages/whoosh/index.py", line 632, in read
[Wed Apr 15 14:04:23 2015] [error]     check_size("int", _INT_SIZE)
[Wed Apr 15 14:04:23 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/python/virtenv/lib/python2.7/site-packages/whoosh/index.py", line 626, in check_size
[Wed Apr 15 14:04:23 2015] [error]     sz = stream.read_varint()
[Wed Apr 15 14:04:23 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/python/virtenv/lib/python2.7/site-packages/whoosh/filedb/structfile.py", line 191, in read_varint
[Wed Apr 15 14:04:23 2015] [error]     return read_varint(self.read)
[Wed Apr 15 14:04:23 2015] [error]   File "/var/lib/openshift/54ca55defcf933aff3000136/python/virtenv/lib/python2.7/site-packages/whoosh/util/varints.py", line 102, in read_varint
[Wed Apr 15 14:04:23 2015] [error]     b = ord(readfn(1))
[Wed Apr 15 14:04:23 2015] [error] TypeError: ord() expected a character, but string of length 0 found
144.9.40.131 - - [15/Apr/2015:14:04:21 -0400] "GET /search/?q=monster&search=ftx&source=on&target=on&type=all&ignored=False HTTP/1.1" 500 7984 "http://weblate-blockstory.rhcloud.com/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36"
```

**Comment by nijel** [comment]
It seems there is something wrong with fulltext index. Maybe it got corrupted when you ran out of free space (#714)? Try rebuilding it by `./manage.py rebuild_index --all --clean`?

**Comment by paulpach** [comment]
Thank you,  this worked.  I have search again\o/
