### ISSUE TITLE
badge.svg missing from release

### ISSUE THREAD

**Issue by wichert** [nijel/weblate#734]
I noticed my weblate 2.2 install is producing a lot of errors about badge.svg not existing:

```
ERROR Internal Server Error: /widgets/public-websites/-/svg-badge.svg
Traceback (most recent call last):
  File "/app/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/local/lib/python2.7/site-packages/django/utils/decorators.py", line 105, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/app/local/lib/python2.7/site-packages/weblate/trans/views/widgets.py", line 142, in render_widget
    widget.render()
  File "/app/local/lib/python2.7/site-packages/weblate/trans/widgets.py", line 411, in render
    'percent_offset': translated_width + percent_width / 2,
  File "/app/local/lib/python2.7/site-packages/django/template/loader.py", line 170, in render_to_string
    t = get_template(template_name, dirs)
  File "/app/local/lib/python2.7/site-packages/django/template/loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "/app/local/lib/python2.7/site-packages/django/template/loader.py", line 136, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: badge.svg
```

**Comment by wichert** [comment]
Looks like MANIFEST.in is missing an entry for the .svg file:

```
recursive-include weblate/html *.svg
```

should fix this.
