### ISSUE TITLE
Error installing weblate

### ISSUE THREAD

**Issue by teopost** [nijel/weblate#744]
Hi, I have this error when I try to install weblate

```bash
Traceback (most recent call last):
  File "/app/bin/django-admin", line 11, in <module>
    sys.exit(execute_from_command_line())
  File "/app/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/app/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/app/local/lib/python2.7/site-packages/django/conf/__init__.py", line 46, in __getattr__
    self._setup(name)
  File "/app/local/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/app/local/lib/python2.7/site-packages/django/conf/__init__.py", line 94, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/app/local/lib/python2.7/site-packages/weblate/__init__.py", line 120, in <module>
    check_data_writable()
  File "/app/local/lib/python2.7/site-packages/weblate/trans/data.py", line 33, in check_data_writable
    os.makedirs(appsettings.DATA_DIR)
  File "/app/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/app/local/lib/python2.7/site-packages/weblate/../data'

```

Can you help me ?

**Comment by nijel** [comment]
Set DATA_DIR to some writable location, see
https://docs.weblate.org/en/latest/admin/config.html#data-dir

-- 
	Michal Čihař | http://cihar.com | http://blog.cihar.com
