### ISSUE TITLE
Index error in views/js.py

### ISSUE THREAD

**Issue by SirAnthony** [nijel/weblate#746]
Hello,
I start to receive a lot of index errors about js.py after upgrade to 2.2 (master does not work for me with template tags errors), I saw it before (in 2.0), but if was about 1 per 2-3 weeks, now it about 10 per night. It seems no units was found by queryset.
We use JSON storage with minimal monkeypatches (10 lines) to overcome translate-toolkit bugs (I think, you remember my commits there).

At second though it seems, this is evil-minded baidu spider which come up with some links, then go there to cause errors.
Probably some minimal check is needed there to return 404 instead of 5xx.

```
Internal Server Error: /js/detail/hola/android/19ef574923215cd2625a433130eb2383/
Traceback (most recent call last):
  File "/opt/weblate/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./weblate/trans/views/js.py", line 198, in get_detail
    source = units[0].source_info
  File "/opt/weblate/local/lib/python2.7/site-packages/django/db/models/query.py", line 201, in __getitem__
    return list(qs)[0]
IndexError: list index out of range

Request repr(): 
<WSGIRequest
path:/js/detail/hola/android/19ef574923215cd2625a433130eb2383/,
GET:<QueryDict: {u'next': [u'/projects/hola/android/source/review/?page=4']}>,
POST:<QueryDict: {}>,
COOKIES:{},
META:{'CONTENT_LENGTH': '',
 'CONTENT_TYPE': '',
 u'CSRF_COOKIE': u'krJFbD0To0oVfnyWIjFZIwg44dOzar7m',
 'DOCUMENT_ROOT': '/usr/share/nginx/html',
 'HTTP_ACCEPT': '*/*',
 'HTTP_ACCEPT_ENCODING': 'gzip',
 'HTTP_ACCEPT_LANGUAGE': 'en-US',
 'HTTP_CONNECTION': 'close',
 'HTTP_HOST': 'translate.hola.org',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html)',
 'PATH_INFO': u'/js/detail/hola/android/19ef574923215cd2625a433130eb2383/',
 'QUERY_STRING': 'next=/projects/hola/android/source/review/?page=4&',
 'REMOTE_ADDR': '180.76.15.137',
 'REMOTE_PORT': '51320',
 'REQUEST_METHOD': 'GET',
 'REQUEST_URI': '/js/detail/hola/android/19ef574923215cd2625a433130eb2383/?next=/projects/hola/android/source/review/?page=4&',
 u'SCRIPT_NAME': u'',
 'SERVER_NAME': 'translate.hola.org',
 'SERVER_PORT': '80',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'uwsgi.node': 'translate',
 'uwsgi.version': '1.9.17.1-debian',
 'wsgi.errors': <open file 'wsgi_errors', mode 'w' at 0x7fd7a21ecdb0>,
 'wsgi.file_wrapper': <built-in function uwsgi_sendfile>,
 'wsgi.input': <uwsgi._Input object at 0x7fd7a0d172e8>,
 'wsgi.multiprocess': True,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}>

Language: None
User: None

Versions:
 * Weblate 2.2
 * Python 2.7.6
 * Django 1.8.1
 * python-social-auth 0.2.9
 * Translate Toolkit 1.13.0
 * Whoosh 2.7.0
 * Git 1.9.1
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.4.4
 * django-crispy-forms 1.4.0
```

Another one is different spider:
```
 'HTTP_USER_AGENT': 'Mozilla/5.0 (compatible; AhrefsBot/5.0; +http://ahrefs.com/robot/)',
```

**Comment by nijel** [comment]
Should be already fixed in b9b07b4f, please upgrade.
