### ISSUE TITLE
Migration problem

### ISSUE THREAD

**Issue by Mikanoshi** [nijel/weblate#752]
```
$ python manage.py migrate
Operations to perform:
  Synchronize unmigrated apps: staticfiles, admindocs, messages, sitemaps, weblate, crispy_forms
  Apply all migrations: lang, sessions, admin, sites, auth, default, contenttypes, accounts, trans
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying accounts.0009_auto_20150607_1424... OK
  Applying lang.0002_auto_20150607_1424... OK
  Applying trans.0031_auto_20150415_1339...Traceback (most recent call last):
  File "manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 221, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 147, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 112, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/operations/special.py", line 183, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/home/toolbox/data/www/l10n.sensetoolbox.com/weblate/trans/migrations/0031_auto_20150415_1339.py", line 19, in fill_in_subproject
    elif change.translation:
  File "/usr/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 602, in __get__
    rel_obj = qs.get()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
__fake__.DoesNotExist: Translation matching query does not exist.
```

**Comment by Mikanoshi** [comment]
Still the same error on line 19...

**Comment by nijel** [comment]
Didn't you manually delete something from the database? What database backend are you using?

**Comment by Mikanoshi** [comment]
I didn't change anything in DB, it's MySQL. What exactly does this migration do? Populates subproject_id column in trans_change table using translation_id? There are ~40 entries with translation_id = NULL.

**Comment by nijel** [comment]
translation_id = NULL shouldn't be problem, it rather seems that there is id of translation which no longer exists ...

**Comment by Mikanoshi** [comment]
Yes, many translation ids are missing. Must be manually removed, but it was long ago and everything was working)
https://gist.github.com/Mikanoshi/9b60b0c8955f0d317cd9

**Comment by nijel** [comment]
Did you disable foreign key constrains? Otherwise the database would not allow you to delete those... Anyway at this point, I'd recommend deleting changes with non existing translation IDs. Even if I would workaround this in the migration, it would explode somewhere else...

**Comment by Mikanoshi** [comment]
Tables are MyISAM. IIRC I removed some languages from `trans_translation` table, now I just change 1 to 0 in `enabled` column, because it is no longer available from Django admin.
Cleaned `trans_change` and migration succeeded. Thanks.
