### ISSUE TITLE
Upgrade from 2.2 to 2.3 fails

### ISSUE THREAD

**Issue by WTBenjamin** [nijel/weblate#770]
We are running a weblate stack from bitnami and are trying to upgrade from 2.2 to 2.3.
After we have imported the mysql dump from weblate 2.2 into the new instance with weblate 2.3 and execute "./manage.py migrate" we get the following error message:

```
/apps/weblate$ sudo ./manage.py migrate
/opt/bitnami/python/lib/python2.7/site-packages/setuptools-7.0-py2.7.egg/pkg_resources.py:1045: UserWarning: /opt/bitnami/.tmp is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
Operations to perform:
  Synchronize unmigrated apps: sitemaps, weblate, crispy_forms
  Apply all migrations: lang, sessions, admin, sites, auth, default, contenttypes, accounts, trans
Synchronizing apps without migrations:
  Creating tables...
  Installing custom SQL...
  Installing indexes...
Running migrations:
  Applying lang.0001_initial... FAKED
  Applying contenttypes.0001_initial... FAKED
  Applying auth.0001_initial... FAKED
  Applying trans.0001_initial... FAKED
  Applying default.0001_initial... FAKED
  Applying accounts.0001_initial... FAKED
  Applying accounts.0002_auto_20140923_1543... OK
  Applying accounts.0003_auto_20141104_1159... OK
  Applying accounts.0004_auto_20150108_1424... OK
  Applying accounts.0005_auto_20150330_1358... OK
  Applying accounts.0006_profile_hide_completed... OK
  Applying accounts.0007_auto_20150427_1505... OK
  Applying accounts.0008_profile_hide_source_secondary... OK
  Applying admin.0001_initial... FAKED
  Applying sessions.0001_initial... FAKED
  Applying sites.0001_initial... FAKED
  Applying trans.0002_auto_20141021_1347...Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/Django-1.7.8-py2.7.egg/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/Django-1.7.8-py2.7.egg/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/Django-1.7.8-py2.7.egg/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/Django-1.7.8-py2.7.egg/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/Django-1.7.8-py2.7.egg/django/core/management/commands/migrate.py", line 161, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/Django-1.7.8-py2.7.egg/django/db/migrations/executor.py", line 68, in migrate
    self.apply_migration(migration, fake=fake)
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/Django-1.7.8-py2.7.egg/django/db/migrations/executor.py", line 102, in apply_migration
    migration.apply(project_state, schema_editor)
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/Django-1.7.8-py2.7.egg/django/db/migrations/migration.py", line 108, in apply
    operation.database_forwards(self.app_label, schema_editor, project_state, new_state)
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/Django-1.7.8-py2.7.egg/django/db/migrations/operations/fields.py", line 37, in database_forwards
    field,
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/Django-1.7.8-py2.7.egg/django/db/backends/mysql/schema.py", line 42, in add_field
    super(DatabaseSchemaEditor, self).add_field(model, field)
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/Django-1.7.8-py2.7.egg/django/db/backends/schema.py", line 388, in add_field
    self.execute(sql, params)
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/Django-1.7.8-py2.7.egg/django/db/backends/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/Django-1.7.8-py2.7.egg/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/Django-1.7.8-py2.7.egg/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/Django-1.7.8-py2.7.egg/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/Django-1.7.8-py2.7.egg/django/db/backends/mysql/base.py", line 129, in execute
    return self.cursor.execute(query, args)
  File "build/bdist.linux-x86_64/egg/MySQLdb/cursors.py", line 173, in execute
  File "build/bdist.linux-x86_64/egg/MySQLdb/connections.py", line 36, in defaulterrorhandler
django.db.utils.OperationalError: (1060, "Duplicate column name 'enable_hooks'")
```

Could you please help us to get our weblate upgraded to 2.3.

Regards
Ben

**Comment by nijel** [comment]
What Django version did you have before and have now?

I've just tried clean install of Weblate 2.2 with Django 1.6 and upgraded to Weblate 2.3 with Django 1.8 it went without problems following instructions in https://docs.weblate.org/en/latest/admin/upgrade.html

**Comment by WTBenjamin** [comment]
The Bitnami Weblate 2.2 Stack comes with Django 1.6.10. The new one has Django 1.7.8 integrated.
We started our work with Bitnami Weblate 2.2 and did no upgrade from previous versions. So this should have been a clean install, too.

We did a backup on the "old" instance with the following steps:
sudo /opt/bitnami/ctlscript.sh stop
mysqldump -u root -p presently > /home/bitnami/weblate_backup.sql
sudo tar -zcvf data.tar.gz apps/weblate/data

We tried to restore our backup on the "new" instance with the following steps:
tar -xf data.tar.gz
mysql -u root -p presently < /home/bitnami/weblate_backup.sql
apps/weblate/manage.py migrate

Did we forget something?

Regards
Ben

**Comment by nijel** [comment]
This sounds pretty much like what I've tested, the only difference being Django 1.8 in the end... Though I'll probably not to get back to this for more testing till Monday.

What you can try (assuming you can play with the data and have the backup still available) is to fake all failing migrations as long as they fail (they have been applied already in earlier version):

```
./manage.py migrate --fake trans 0002_auto_20141021_1347
```

**Comment by WTBenjamin** [comment]
I skipped the following steps because they had duplicate columns:
```
0002_auto_20141021_1347
0004_auto_20141021_1550
```
But now I get a different error which I don't know if I should skip it:
```
/apps/weblate$ sudo ./manage.py migrate
/opt/bitnami/python/lib/python2.7/site-packages/setuptools-7.0-py2.7.egg/pkg_resources.py:1045: UserWarning: /opt/bitnami/.tmp is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
Operations to perform:
  Synchronize unmigrated apps: sitemaps, weblate, crispy_forms
  Apply all migrations: lang, sessions, admin, sites, auth, default, contenttypes, accounts, trans
Synchronizing apps without migrations:
  Creating tables...
  Installing custom SQL...
  Installing indexes...
Running migrations:
  Applying trans.0005_auto_20141021_1550...Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/Django-1.7.8-py2.7.egg/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/Django-1.7.8-py2.7.egg/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/Django-1.7.8-py2.7.egg/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/Django-1.7.8-py2.7.egg/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/Django-1.7.8-py2.7.egg/django/core/management/commands/migrate.py", line 161, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/Django-1.7.8-py2.7.egg/django/db/migrations/executor.py", line 68, in migrate
    self.apply_migration(migration, fake=fake)
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/Django-1.7.8-py2.7.egg/django/db/migrations/executor.py", line 102, in apply_migration
    migration.apply(project_state, schema_editor)
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/Django-1.7.8-py2.7.egg/django/db/migrations/migration.py", line 105, in apply
    operation.database_forwards(self.app_label, schema_editor, project_state, new_state)
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/Django-1.7.8-py2.7.egg/django/db/migrations/operations/special.py", line 117, in database_forwards
    self.code(from_state.render(), schema_editor)
  File "/opt/bitnami/apps/weblate/weblate/trans/migrations/0005_auto_20141021_1550.py", line 10, in fill_in_fields
    subproject.license = subproject.project.license
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/Django-1.7.8-py2.7.egg/django/db/models/fields/related.py", line 572, in __get__
    rel_obj = qs.get()
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/Django-1.7.8-py2.7.egg/django/db/models/query.py", line 351, in get
    num = len(clone)
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/Django-1.7.8-py2.7.egg/django/db/models/query.py", line 122, in __len__
    self._fetch_all()
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/Django-1.7.8-py2.7.egg/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/Django-1.7.8-py2.7.egg/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/Django-1.7.8-py2.7.egg/django/db/models/sql/compiler.py", line 701, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/Django-1.7.8-py2.7.egg/django/db/models/sql/compiler.py", line 787, in execute_sql
    cursor.execute(sql, params)
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/Django-1.7.8-py2.7.egg/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/Django-1.7.8-py2.7.egg/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/Django-1.7.8-py2.7.egg/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/opt/bitnami/apps/django/lib/python2.7/site-packages/Django-1.7.8-py2.7.egg/django/db/backends/mysql/base.py", line 129, in execute
    return self.cursor.execute(query, args)
  File "build/bdist.linux-x86_64/egg/MySQLdb/cursors.py", line 173, in execute
  File "build/bdist.linux-x86_64/egg/MySQLdb/connections.py", line 36, in defaulterrorhandler
django.db.utils.OperationalError: (1054, "Unknown column 'trans_project.license' in 'field list'")
```

**Comment by nijel** [comment]
You need to fake more of them, I've just updated documentation to cover this corner case. It was not seen so far as most of users have upgraded to Django 1.7/1.8 on Weblate 2.2 or before...

**Comment by nijel** [comment]
See: https://docs.weblate.org/en/latest/admin/upgrade.html#upgrade-from-2-2-to-2-3
