### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by peterpostmann** [nijel/weblate#797]
If "SITE_TITLE" in "weblate/settings.py" containts unicode charachters (like german umauts ä,ö,ü) 

the function "send_notification_email" in "weblate/accounts/models.py" fails

```
INFO:weblate:Passed captcha for *******@gmail.com (13 - 7 = 6)
INFO:weblate:sending notification activation on dccf2a46ab484d4eb660f5e05f89b105 to *******@gmail.com
ERROR:django.request:Internal Server Error: /accounts/register/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/weblate/weblate/accounts/views.py", line 409, in register
    return complete(request, 'email')
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/social/apps/django_app/utils.py", line 51, in wrapper
    return func(request, backend, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/social/apps/django_app/views.py", line 28, in complete
    redirect_name=REDIRECT_FIELD_NAME, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/social/actions.py", line 43, in do_complete
    user = backend.complete(user=user, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/social/backends/base.py", line 41, in complete
    return self.auth_complete(*args, **kwargs)
  File "/opt/weblate/weblate/accounts/auth.py", line 41, in auth_complete
    return super(EmailAuth, self).auth_complete(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/social/backends/legacy.py", line 25, in auth_complete
    return self.strategy.authenticate(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/social/strategies/django_strategy.py", line 96, in authenticate
    return authenticate(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 74, in authenticate
    user = backend.authenticate(**credentials)
  File "/usr/local/lib/python2.7/dist-packages/social/backends/base.py", line 82, in authenticate
    return self.pipeline(pipeline, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/social/backends/base.py", line 85, in pipeline
    out = self.run_pipeline(pipeline, pipeline_index, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/social/backends/base.py", line 112, in run_pipeline
    result = func(*args, **out) or {}
  File "/usr/local/lib/python2.7/dist-packages/social/pipeline/partial.py", line 15, in wrapper
    *args, **kwargs) or {}
  File "/usr/local/lib/python2.7/dist-packages/social/pipeline/mail.py", line 19, in mail_validation
    backend.strategy.send_email_validation(backend, details['email'])
  File "/usr/local/lib/python2.7/dist-packages/social/strategies/base.py", line 127, in send_email_validation
    send_email(self, backend, code)
  File "/opt/weblate/weblate/accounts/pipeline.py", line 77, in send_validation
    'url': url
  File "/opt/weblate/weblate/accounts/models.py", line 264, in send_notification_email
    settings.EMAIL_SUBJECT_PREFIX + subject,
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 13: ordinal not in range(128)
```

if admin mail is set, "/usr/local/lib/python2.7/dist-packages/django/core/mail/__init__.py" fails subsequently.

```
mod_wsgi (pid=1392): Exception occurred processing WSGI script '/opt/weblate/weblate/wsgi.py'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 256, in handle_uncaught_exception
    'request': request
  File "/usr/lib/python2.7/logging/__init__.py", line 1178, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1271, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1281, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1321, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 749, in handle
    self.emit(record)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/log.py", line 129, in emit
    self.send_mail(subject, message, fail_silently=True, html_message=html_message)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/log.py", line 132, in send_mail
    mail.mail_admins(subject, message, *args, connection=self.connection(), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/mail/__init__.py", line 93, in mail_admins
    mail = EmailMultiAlternatives('%s%s' % (settings.EMAIL_SUBJECT_PREFIX, subject),
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 13: ordinal not in range(128)
```

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 13: ordinal not in range(128)

**Comment by nijel** [comment]
Can you try setting it as unicode string in settings.py? I think it should work. For example: ```SITE_TITLE = u' ä,ö,ü'```
