### ISSUE TITLE
TemplateSyntaxError: 'compress' is not a valid tag library

### ISSUE THREAD

**Issue by whedro** [nijel/weblate#824]
Hi nigel, 

pls help with this .... what I forgot install or upgrade ?
Michal

Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/weblate/weblate/trans/views/basic.py", line 99, in home
    'whiteboard_messages': wb_messages,
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python2.7/dist-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 917, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 113, in render
    compiled_parent = self.get_parent(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 110, in get_parent
    return context.template.engine.get_template(parent)
  File "/usr/local/lib/python2.7/dist-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loaders/cached.py", line 62, in load_template
    template, origin = self.find_template(template_name, template_dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loaders/cached.py", line 41, in find_template
    template, display_name = loader(name, dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/usr/local/lib/python2.7/dist-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 1163, in load
    (taglib, e))
TemplateSyntaxError: 'compress' is not a valid tag library: Template library compress not found, tried django.templatetags.compress,django.contrib.staticfiles.templatetags.compress,django.contrib.admin.templatetags.compress,crispy_forms.templatetags.compress,weblate.trans.templatetags.compress,weblate.accounts.templatetags.compress

Language: None
User: u'whedro'

Versions:
 * Weblate weblate-2.3-771-gf33bd3b
 * Python 2.7.6
 * Django 1.8.4
 * python-social-auth 0.2.12
 * Translate Toolkit 1.13.0
 * Whoosh 2.7.0
 * Git 1.9.1
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.4.4
 * django-crispy-forms 1.5.1
 * compressor 1.5
 * pyuca N/A
 * pyLibravatar N/A
 * Mercurial 3.5

**Comment by whedro** [comment]
Admin works fine

**Comment by whedro** [comment]
Hi, 

I looked into commits and find change in settings.py ...
After add new lines in my settings.py I was other error ...

 mod_wsgi (pid=2580): Target WSGI script '/opt/weblate/weblate/wsgi.py' cannot be loaded as Python module.
 mod_wsgi (pid=2580): Exception occurred processing WSGI script '/opt/weblate/weblate/wsgi.py'.
 Traceback (most recent call last):
   File "/opt/weblate/weblate/wsgi.py", line 44, in <module>
     application = get_wsgi_application()
   File "/usr/local/lib/python2.7/dist-packages/django/core/wsgi.py", line 14, in get_wsgi_application
     django.setup()
   File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
     apps.populate(settings.INSTALLED_APPS)
   File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
     app_config = AppConfig.create(entry)
   File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 86, in create
     module = import_module(entry)
   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
     __import__(name)
 ImportError: No module named compress

**Comment by whedro** [comment]
OK .. my fault again .... module have name "compressor" not "compress"

**Comment by nijel** [comment]
Thanks for reminding me, I've added this new dependency to upgrading instructions.

**Comment by Rvanlaak** [comment]
Do also get this error after doing `git pull` on master. Did install the additional dependency:

    pip install django_compressor

Unfortunately the error stil occurs. Did I install the wrong dependency? Also tried to solve it by installing from the requirements file:

    sudo pip install -r requirements.txt --upgrade

**Comment by nijel** [comment]
You need to adjust settings.py as well (but seems you have already figured it out).

As for the static files, that's already covered by the upgrading docs, but I'm adding some clarifications there.

**Comment by nijel** [comment]
I hope the upgrading instructions are now complete:

https://docs.weblate.org/en/latest/admin/upgrade.html#upgrade-from-2-3-to-2-4

Please let me know if something you had to do is still missing.

**Comment by Rvanlaak** [comment]
The `/data/static` is identical to `/weblate/static` ?

**Comment by nijel** [comment]
No, ``data/static`` is generated by ``./manage.py collectstatic`` + is used as cache for generated content. The ``weblate/static`` is only part of files which are copied/linked to ``data/static``.

You can find more information on https://docs.djangoproject.com/en/1.8/howto/static-files/deployment/

**Comment by Rvanlaak** [comment]
Thanks! I've read through your documentation and used the commands and updated my vhost, and finally managed to resolve the static files. We run weblate under a path using URL_PREFIX, doesn't seems to function optimal with all those paths in the config file.

```vhost
WSGIPythonPath /var/www/weblate
WSGIScriptAlias /weblate /var/www/weblate/weblate/wsgi.py

Alias /weblate/robots.txt /var/www/weblate/weblate/static/robots.txt
Alias /weblate/favicon.ico /var/www/weblate/weblate/static/favicon.ico

Alias /weblate/doc/ /var/www/weblate/weblate/html/
Alias /weblate/static/ /var/www/weblate/weblate/static/

<Directory /var/www/weblate/weblate>
   <Files wsgi.py>
       Order deny,allow
       Allow from all
   </Files>
</Directory>

```
https://docs.weblate.org/en/latest/admin/install.html#sample-configuration-for-apache

**Comment by nijel** [comment]
I've just updated https://docs.weblate.org/en/latest/admin/install.html#running-weblate-under-path to include complete Apache configuration. You should use ``data/static`` in the Apache conf. Also the ``/doc`` alias is not needed at all.
