### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'id'

### ISSUE THREAD

**Issue by daniele-athome** [nijel/weblate#882]
I got this email error report, but I can't trace what the user was doing, sorry.

```
Internal Server Error: /translate/kontalk-androidclient/app/fa/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hosting/weblate-dev/weblate/trans/views/edit.py", line 524, in translate
    this_unit_url, next_unit_url
  File "/home/hosting/weblate-dev/weblate/trans/views/edit.py", line 293, in handle_translate
    go_next = perform_suggestion(unit, form, request)
  File "/home/hosting/weblate-dev/weblate/trans/views/edit.py", line 211, in perform_suggestion
    request,
  File "/home/hosting/weblate-dev/weblate/trans/models/unitdata.py", line 64, in add
    if can_vote_suggestion(user, unit.translation):
  File "/home/hosting/weblate-dev/weblate/trans/permissions.py", line 59, in wrapper
    return func(user, target_object)
  File "/home/hosting/weblate-dev/weblate/trans/permissions.py", line 136, in can_vote_suggestion
    if check_owner(user, project, 'trans.vote_suggestion'):
  File "/home/hosting/weblate-dev/weblate/trans/permissions.py", line 33, in check_owner
    if not project.owners.filter(id=user.id).exists():
AttributeError: 'NoneType' object has no attribute 'id'

Request repr():
<WSGIRequest
path:/translate/kontalk-androidclient/app/fa/,
GET:<QueryDict: {u'offset': [u'0'], u'sid': [u'da7c1e64-7772-11e5-ae1f-040110ebe801']}>,
POST:<QueryDict: {u'checksum': [u'967274a452271f543a4d0165bfd00fae'], u'rtl-id_967274a452271f543a4d0165bfd00fae_0': [u'rtl'], u'content': [u''], u'suggest': [u'Suggest'], u'csrfmiddlewaretoken': [u'EZ6I9Qx12NkzzZm8DqikdIf1IIvtlQVl'], u'target_0': [u'\u0628\u0647 \u0632\u0648\u062f\u06cc \u0628\u0627\u06cc\u062f \u06cc\u06a9 \u062a\u0645\u0627\u0633 \u0627\u0632 \u062f\u0633\u062a \u0631\u0641\u062a\u0647 \u0627\u0632 \u0627\u06cc\u0646 \u0634\u0645\u0627\u0631\u0647 \u062f\u0631\u06cc\u0627\u0641\u062a \u06a9\u0646\u06cc\u062f. <b>\u0644\u0637\u0641\u0627\u064b \u0628\u0647 \u062a\u0645\u0627\u0633 \u067e\u0627\u0633\u062e \u0646\u062f\u0647\u06cc\u062f.</b>']}>,
META:{'CONTENT_LENGTH': '601',
 'CONTENT_TYPE': 'application/x-www-form-urlencoded',
 'DOCUMENT_ROOT': '/var/www',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTPS': 'on',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'fa-IR,fa;q=0.8,en;q=0.5,en-US;q=0.3',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_CONTENT_LENGTH': '601',
 'HTTP_DNT': '1',
 'HTTP_HOST': 'translate.kontalk.org',
 'HTTP_REFERER': 'https://translate.kontalk.org/translate/kontalk-androidclient/app/fa/?type=untranslated',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0',
 'PATH_INFO': u'/translate/kontalk-androidclient/app/fa/',
 'PATH_TRANSLATED': '/var/www/translate/kontalk-androidclient/app/fa/',
 'QUERY_STRING': 'sid=da7c1e64-7772-11e5-ae1f-040110ebe801&offset=0',
 'REDIRECT_STATUS': '200',
 'REDIRECT_URI': '/weblate.fcgi/translate/kontalk-androidclient/app/fa/?sid=da7c1e64-7772-11e5-ae1f-040110ebe801&offset=0',
 'REMOTE_ADDR': '91.185.157.232',
 'REMOTE_PORT': '17705',
 'REQUEST_METHOD': 'POST',
 'REQUEST_URI': '/translate/kontalk-androidclient/app/fa/?sid=da7c1e64-7772-11e5-ae1f-040110ebe801&offset=0',
 'SCRIPT_FILENAME': '/var/www/weblate.fcgi',
 'SCRIPT_NAME': u'',
 'SERVER_ADDR': '188.226.157.146',
 'SERVER_NAME': 'translate.kontalk.org',
 'SERVER_PORT': '443',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'lighttpd/1.4.35',
 'wsgi.errors': <flup.server.fcgi_base.TeeOutputStream object at 0x58f4750>,
 'wsgi.input': <flup.server.fcgi_base.InputStream object at 0x4f122d0>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'https',
 'wsgi.version': (1, 0)}>

Language: None
User: None

Versions:
 * Weblate weblate-2.4
 * Python 2.7.3
 * Django 1.8.2
 * python-social-auth 0.2.9
 * Translate Toolkit 1.13.0
 * Whoosh 2.7.0
 * Git 1.7.10.4
 * Pillow (PIL) 1.1.7
 * dateutil 1.5
 * lxml 3.4.4
 * django-crispy-forms 1.4.0
 * compressor 1.5
 * pyuca N/A
 * pyLibravatar N/A
```

**Comment by daniele-athome** [comment]
That was fast. Thanks! :-)
