### ISSUE TITLE
Illegal mix of collations

### ISSUE THREAD

**Issue by anj4u** [nijel/weblate#916]
After adding a component (git), I get in the logfile the error on wrong mix of collations. This is the version 2.4. It worked earlier with version 1.6 dev.
The po-files are all utf-8 encoded, so what can I do, to fix it?

[root@vs502 weblate]# tail -f /var/log/weblate/weblate.log

2015-11-02 17:10:26,335 INFO office/core: updating repository
2015-11-02 17:10:27,683 INFO office/core: update took 1.35 seconds:
2015-11-02 17:10:27,683 DEBUG office/core: update: Fetching origin
2015-11-02 17:10:27,767 INFO office/core: merge remote into repo
2015-11-02 17:10:28,103 INFO office/core: updating repository
2015-11-02 17:10:29,394 INFO office/core: update took 1.29 seconds:
2015-11-02 17:10:29,395 DEBUG office/core: update: Fetching origin
2015-11-02 17:10:29,479 INFO office/core: merge remote into repo
2015-11-02 17:10:29,483 INFO office/core: checking lang/po/de_DE.po (de_DE) [1/6]
2015-11-02 17:10:29,507 INFO office/core/de: processing lang/po/de_DE.po, revision has changed
2015-11-02 17:11:28,416 INFO office/core: checking lang/po/en_EN.po (en_EN) [2/6]
2015-11-02 17:11:28,433 INFO office/core/en_EN: processing lang/po/en_EN.po, revision has changed
2015-11-02 17:12:19,947 INFO office/core: checking lang/po/es_ES.po (es_ES) [3/6]
2015-11-02 17:12:19,968 INFO office/core/es: processing lang/po/es_ES.po, revision has changed
2015-11-02 17:13:00,098 INFO office/core: checking lang/po/fr_FR.po (fr_FR) [4/6]
2015-11-02 17:13:00,109 INFO office/core/fr: processing lang/po/fr_FR.po, revision has changed
2015-11-02 17:13:41,552 INFO office/core: checking lang/po/it_IT.po (it_IT) [5/6]
2015-11-02 17:13:41,573 INFO office/core/it: processing lang/po/it_IT.po, revision has changed
2015-11-02 17:14:22,230 INFO office/core: checking lang/po/pl_PL.po (pl_PL) [6/6]
2015-11-02 17:14:22,253 INFO office/core/pl: processing lang/po/pl_PL.po, revision has changed
2015-11-02 17:14:22,622 ERROR Internal Server Error: /admin/trans/subproject/add/
Traceback (most recent call last):
  File "/home/user/weblate-env/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/weblate-env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/user/weblate-env/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/user/weblate-env/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/user/weblate-env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/home/user/weblate-env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1516, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/user/weblate-env/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/user/weblate-env/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/user/weblate-env/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/user/weblate-env/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/home/user/weblate-env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1467, in changeform_view
    self.save_model(request, new_object, form, not add)
  File "/home/user/weblate-env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1078, in save_model
    obj.save()
  File "/home/user/Weblate-2.4/weblate/trans/models/subproject.py", line 1360, in save
    self.create_translations()
  File "/home/user/Weblate-2.4/weblate/trans/models/subproject.py", line 1007, in create_translations
    self, lang, code, path, force, request=request
  File "/home/user/Weblate-2.4/weblate/trans/models/translation.py", line 68, in check_sync
    translation.check_sync(force, request=request)
  File "/home/user/Weblate-2.4/weblate/trans/models/translation.py", line 490, in check_sync
    self, unit, pos
  File "/home/user/Weblate-2.4/weblate/trans/models/unit.py", line 99, in update_from_unit
    dbunit.update_from_unit(unit, pos, created)
  File "/home/user/Weblate-2.4/weblate/trans/models/unit.py", line 468, in update_from_unit
    same_state=same_state
  File "/home/user/Weblate-2.4/weblate/trans/models/unit.py", line 730, in save
    self.run_checks(same_state, same_content, force_insert)
  File "/home/user/Weblate-2.4/weblate/trans/models/unit.py", line 899, in run_checks
    if check_obj.target and check_obj.check_target(src, tgt, self):
  File "/home/user/Weblate-2.4/weblate/trans/checks/base.py", line 57, in check_target
    return self.check_target_unit(sources, targets, unit)
  File "/home/user/Weblate-2.4/weblate/trans/checks/consistency.py", line 79, in check_target_unit
    return related.exists()
  File "/home/user/weblate-env/lib/python2.7/site-packages/django/db/models/query.py", line 586, in exists
    return self.query.has_results(using=self.db)
  File "/home/user/weblate-env/lib/python2.7/site-packages/django/db/models/sql/query.py", line 484, in has_results
    return compiler.has_results()
  File "/home/user/weblate-env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 811, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/home/user/weblate-env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/home/user/weblate-env/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/user/weblate-env/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/user/weblate-env/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/user/weblate-env/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/home/user/weblate-env/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/user/weblate-env/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1267, "Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '<>'")

**Comment by anj4u** [comment]
Found the error, it was the wrong collation of the db and the tables.
