### ISSUE TITLE
fail on filling up MySQL database

### ISSUE THREAD

**Issue by fernandopsilveira** [nijel/weblate#938]
[Install documentation](https://docs.weblate.org/en/latest/admin/install.html) instructs to create MySQL database using utf8mb4 character set, but it fails filling database on `./manage.py migrate` command:

    Operations to perform:
      Synchronize unmigrated apps: staticfiles, admindocs, messages, sitemaps, compressor, weblate, crispy_forms
      Apply all migrations: lang, sessions, admin, sites, auth, default, contenttypes, accounts, trans
    Synchronizing apps without migrations:
      Creating tables...
        Running deferred SQL...
      Installing custom SQL...
    Running migrations:
      Rendering model states... DONE
      Applying lang.0001_initial... OK
      Applying contenttypes.0001_initial... OK
      Applying auth.0001_initial... OK
      Applying trans.0001_initial...Traceback (most recent call last):
      File "./manage.py", line 31, in <module>
        execute_from_command_line(sys.argv)
      File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
        utility.execute()
    (...)
      File "/usr/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
        raise errorclass, errorvalue
    django.db.utils.OperationalError: (1709, 'Index column size too large. The maximum column size is 767 bytes.')

Probably some error creating an UNIQUE index somewhere.

It works if I change table to utf8 charset, but that's not no the ideal solution; specifying a subset of the column rather than the entire amount when creating that index, maybe?

**Comment by nijel** [comment]
This MySQL limitation can IMHO be lifted by setting [innodb_large_prefix](http://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_large_prefix).

**Comment by fernandopsilveira** [comment]
Yes, but only if using Barracuda as Inno file format; furthermore it would be necessary set `ROW_FORMAT=DYNAMIC` when the table is created, or at least, alter the table before the index is created, which is not possible.

**Comment by nijel** [comment]
Indeed it needs some tweaking. I think I've found the guilty field and adjusted it's length. Can you please check it now?

**Comment by fernandopsilveira** [comment]
Still getting it:

    **Running migrations:**
      Rendering model states... DONE
      Applying lang.0001_initial... OK
      Applying contenttypes.0001_initial... OK
      Applying auth.0001_initial... OK
      Applying trans.0001_initial... OK
      Applying default.0001_initial...Traceback (most recent call last):
      File "./manage.py", line 31, in <module>
        execute_from_command_line(sys.argv)
      File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
        utility.execute()
      File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
        self.execute(*args, **cmd_options)
      File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
        output = self.handle(*args, **options)
      File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
        executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
      File "/usr/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
        self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
      File "/usr/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
        state = migration.apply(state, schema_editor)
      File "/usr/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
        operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
      File "/usr/local/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 359, in database_forwards
        getattr(new_model._meta, self.option_name, set()),
      File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 324, in alter_unique_together
        self.execute(self._create_unique_sql(model, columns))
      File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 111, in execute
        cursor.execute(sql, params)
      File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
        return super(CursorDebugWrapper, self).execute(sql, params)
      File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
        return self.cursor.execute(sql, params)
      File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
        six.reraise(dj_exc_type, dj_exc_value, traceback)
      File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
        return self.cursor.execute(sql, params)
      File "/usr/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
        return self.cursor.execute(query, args)
      File "/usr/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
        self.errorhandler(self, exc, value)
      File "/usr/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
        raise errorclass, errorvalue
    django.db.utils.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')

**Comment by nijel** [comment]
Hmm, that's from python-social-auth now... So the utf8mb4 really won't work without innodb_large_prefix...

**Comment by fernandopsilveira** [comment]
Great! Thanks

**Comment by servomac** [comment]
I have the same problem, with a mariadb:10.1 image, creating the weblate database with utf8mb4 and with a `SET GLOBAL innodb_large_prefix = 1` :(

**Comment by nijel** [comment]
There seems to be workaround in python-social-auth for this, see https://github.com/omab/python-social-auth/issues/777
