### ISSUE TITLE
Internal Server Error when suggesting without being logged in

### ISSUE THREAD

**Issue by pc-jedi** [nijel/weblate#968]
```
Internal Server Error: /translate/sites/xxx/de/
Traceback (most recent call last):
  File "/app/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/local/lib/python2.7/site-packages/weblate/trans/views/edit.py", line 524, in translate
    this_unit_url, next_unit_url
  File "/app/local/lib/python2.7/site-packages/weblate/trans/views/edit.py", line 293, in handle_translate
    go_next = perform_suggestion(unit, form, request)
  File "/app/local/lib/python2.7/site-packages/weblate/trans/views/edit.py", line 211, in perform_suggestion
    request,
  File "/app/local/lib/python2.7/site-packages/weblate/trans/models/unitdata.py", line 64, in add
    if can_vote_suggestion(user, unit.translation):
  File "/app/local/lib/python2.7/site-packages/weblate/trans/permissions.py", line 59, in wrapper
    return func(user, target_object)
  File "/app/local/lib/python2.7/site-packages/weblate/trans/permissions.py", line 136, in can_vote_suggestion
    if check_owner(user, project, 'trans.vote_suggestion'):
  File "/app/local/lib/python2.7/site-packages/weblate/trans/permissions.py", line 33, in check_owner
    if not project.owners.filter(id=user.id).exists():
AttributeError: 'NoneType' object has no attribute 'id'


Language: None
User: None

Versions:
 * Weblate 2.4
 * Python 2.7.9
 * Django 1.8.3
 * python-social-auth 0.2.12
 * Translate Toolkit 1.13.0
 * Whoosh 2.7.0
 * Git 2.1.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.4.0
 * django-crispy-forms 1.5.2
 * compressor 1.5
 * pyuca N/A
 * pyLibravatar N/A
 * Mercurial 3.1.2
```
The user group `guest` has the permission to add and vote suggestions.

**Comment by nijel** [comment]
This has been already fixed in git, see #882.
